/**
 * The event catalog — TINKER_UI_DESIGN_BIBLE/logging.md §4 as data (§9 step 1).
 *
 * Single source in code for what may ever be recorded. The writer (logging.md §7.5, §9 step 3)
 * will reject any name or field key this catalog does not declare (counted, never thrown), and
 * the schema module (§9 step 2) seeds the database's `catalog` table and generates per-event
 * views from these rows. logging.md §4 is the human-readable a-priori declaration (L2: declare
 * before emit); `scripts/bible/logging-catalog.mjs` — this optic's `verify:` — checks that the
 * two agree in BOTH directions on every run, so neither can drift silently.
 *
 * FORMAT CONTRACT: scripts/bible/logging-catalog.mjs parses this file TEXTUALLY (it runs under
 * plain node, with no TypeScript loader). Every row keeps its first three properties — the
 * event's dotted identifier, its kind and its retention class — double-quoted, each on its own
 * line, in that order. Never give a declared field key one of those three property names;
 * catalog.test.ts enforces both halves of this contract.
 *
 * PII (logging.md L4): a string-typed field is "enum" (a closed set) or "id" (pattern-limited,
 * at most 64 characters); there is no free-text field type, so the writer can drop anything else
 * mechanically. "json" is reserved for the structured objects §4 itself names (the algorithm
 * ledger's metrics/provenance/config, histogram buckets, per-reason counters), which carry no
 * free text by their own rules.
 */

export const EVENT_KINDS = ["sample", "span", "transition", "outcome", "rollup", "mark"] as const;
export type EventKind = (typeof EVENT_KINDS)[number];

export const RETENTION_CLASSES = ["hot", "event", "research", "debug"] as const;
export type RetentionClass = (typeof RETENTION_CLASSES)[number];

/** L4: no free-text type exists. Strings are "enum" (closed set) or "id" (pattern-limited). */
export const FIELD_TYPES = ["number", "boolean", "enum", "id", "json"] as const;
export type CatalogFieldType = (typeof FIELD_TYPES)[number];

/** The J-series papers (logging.md §6); `catalog.paper` in the schema (§7.3). */
export type JSeriesPaper =
  | "J1"
  | "J2"
  | "J3"
  | "J4"
  | "J5"
  | "J6"
  | "J7"
  | "J8"
  | "J9"
  | "J10"
  | "J11"
  | "J12"
  | "J13"
  | "J14"
  | "J15"
  | "J16"
  | "J17"
  | "J18"
  | "J19"
  | "J20";

export interface CatalogEvent {
  /** Stable dotted name, `<domain>.<object>[.<verb>]` (L1); the primary key. */
  readonly name: string;
  /** §4 Kinds: sample, span, transition, outcome, rollup, mark. */
  readonly kind: EventKind;
  /** Retention class (§7.4): hot, event, research, debug. */
  readonly retention: RetentionClass;
  /** The J-series paper whose metric this row carries (§4.12), else null. */
  readonly paper: JSeriesPaper | null;
  /** The question this event exists to answer (L2). */
  readonly question: string;
  /** What `label` — the one categorical dimension — carries, or null when unused. */
  readonly label: string | null;
  /** What `dur_ms` measures, or null when unused; every span states it. */
  readonly durMs: string | null;
  /** What n1..n4 carry (unit in the name, L1), or null when unused. */
  readonly n1: string | null;
  readonly n2: string | null;
  readonly n3: string | null;
  readonly n4: string | null;
  /** Declared `fields` JSON keys with their types (L4). */
  readonly fields: Readonly<Record<string, CatalogFieldType>>;
  /** May this row arrive through `logs.ingest` from the UI (§8.2)? Gateway events never. */
  readonly uiIngestable: boolean;
}

/** L1 name grammar — identical to the one the frontmatter gate checks over §4. */
export const EVENT_NAME_PATTERN = /^[a-z][a-z0-9_]*(?:\.[a-z0-9_]+)+$/;

export const EVENT_CATALOG: readonly CatalogEvent[] = [
  // ── §4.1 Gateway health ─────────────────────────────────────────────────────
  {
    name: "gw.boot",
    kind: "mark",
    retention: "event",
    paper: null,
    question: "Which build was running when a trend changed?",
    label: "build commit",
    durMs: null,
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    fields: { node_version: "id", plugin_count: "number", config_hash: "id" },
    uiIngestable: false,
  },
  {
    name: "gw.health.sample",
    kind: "sample",
    retention: "hot",
    paper: null,
    question: "Is the main thread keeping up, and is it trending worse over days?",
    label: null,
    durMs: null,
    n1: "loop_p99_ms",
    n2: "loop_max_ms",
    n3: "elu",
    n4: "cpu_core_ratio",
    fields: {
      gc_count: "number",
      gc_ms: "number",
      gc_max_pause_ms: "number",
      active: "number",
      waiting: "number",
      queued: "number",
    },
    uiIngestable: false,
  },
  {
    name: "gw.liveness.warning",
    kind: "mark",
    retention: "event",
    paper: null,
    question: "When did the loop cross the existing warning bars, and what was in flight?",
    label: "reasons joined by +",
    durMs: null,
    n1: "loop_p99_ms",
    n2: "loop_max_ms",
    n3: "elu",
    n4: "cpu_core_ratio",
    fields: {},
    uiIngestable: false,
  },
  {
    name: "gw.memory.pressure",
    kind: "mark",
    retention: "event",
    paper: null,
    question: "When did memory cross a pressure threshold, and was it growth or level?",
    label: "level:reason",
    durMs: null,
    n1: "rss_bytes",
    n2: "heap_used_bytes",
    n3: "threshold_bytes",
    n4: "rss_growth_bytes",
    fields: {},
    uiIngestable: false,
  },
  {
    name: "gw.session.stuck",
    kind: "mark",
    retention: "event",
    paper: null,
    question: "Which sessions stall, for how long, and for which reason?",
    label: "state",
    durMs: null,
    n1: "age_ms",
    n2: "queue_depth",
    n3: null,
    n4: null,
    fields: { reason: "enum" },
    uiIngestable: false,
  },
  {
    name: "gw.profile.captured",
    kind: "mark",
    retention: "event",
    paper: null,
    question: "Was a CPU profile taken during this incident, and which one?",
    label: null,
    durMs: null,
    n1: "duration_ms",
    n2: "samples",
    n3: null,
    n4: null,
    fields: { profile_id: "id" },
    uiIngestable: false,
  },
  // ── §4.2 RPC ────────────────────────────────────────────────────────────────
  {
    name: "rpc.minute",
    kind: "rollup",
    retention: "hot",
    paper: null,
    question:
      "Which methods cost the main thread most per minute, and does that track loop stalls?",
    label: "method",
    durMs: null,
    n1: "calls",
    n2: "total_ms",
    n3: "max_ms",
    n4: "errors",
    fields: { refused: "number", refusal_reasons: "json", hist_ms: "json" },
    uiIngestable: false,
  },
  {
    name: "rpc.slow",
    kind: "span",
    retention: "event",
    paper: null,
    question: "Which individual calls were outliers for their own method?",
    label: "method",
    durMs: "handler time of one outlier call",
    n1: "response_bytes",
    n2: null,
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  // ── §4.3 Session store and locks ────────────────────────────────────────────
  {
    name: "store.lock.held",
    kind: "span",
    retention: "hot",
    paper: null,
    question: "How long do session-store writers wait and hold, per call site, per day?",
    label: "site",
    durMs: "hold",
    n1: "wait_ms",
    n2: "queue_depth",
    n3: "timeout_ms",
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "store.lock.timeout",
    kind: "mark",
    retention: "event",
    paper: null,
    question: "Which writers gave up waiting for the store lock?",
    label: "site",
    durMs: null,
    n1: "wait_ms",
    n2: "queue_depth",
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "store.save",
    kind: "span",
    retention: "hot",
    paper: null,
    question: "Is the session store growing, and how long does one save hold the loop?",
    label: null,
    durMs: "save",
    n1: "bytes_written",
    n2: "entries",
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "lock.watchdog.release",
    kind: "mark",
    retention: "event",
    paper: null,
    question: "Did any lock outlive its max hold, and of which kind?",
    label: null,
    durMs: null,
    n1: "held_ms",
    n2: "max_hold_ms",
    n3: null,
    n4: null,
    fields: { lock_kind: "enum" },
    uiIngestable: false,
  },
  // ── §4.4 Transcript index and chat.history ──────────────────────────────────
  {
    name: "transcript.index.minute",
    kind: "rollup",
    retention: "hot",
    paper: null,
    question: "Is history served from the index or rebuilt, and does the working set fit the cap?",
    label: null,
    durMs: null,
    n1: "noops",
    n2: "tail_parses",
    n3: "full_builds",
    n4: "evictions",
    fields: {
      thrash_evictions: "number",
      registry_entries: "number",
      registry_bytes: "number",
      cap_bytes: "number",
    },
    uiIngestable: false,
  },
  {
    name: "transcript.index.build",
    kind: "span",
    retention: "event",
    paper: null,
    question: "What does a full rebuild cost, and why did it happen?",
    label: "cause (first, rewrite, inode)",
    durMs: "full build",
    n1: "file_bytes",
    n2: "entries",
    n3: "unindexed_lines",
    n4: "duplicate_ids",
    fields: {},
    uiIngestable: false,
  },
  {
    name: "transcript.index.thrash",
    kind: "mark",
    retention: "event",
    paper: null,
    question: "Is the byte cap below the open-tab working set?",
    label: null,
    durMs: null,
    n1: "age_ms",
    n2: "cap_bytes",
    n3: "registry_entries",
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "transcript.legacy_fallback",
    kind: "mark",
    retention: "event",
    paper: null,
    question: "Which transcripts still pay the whole-file re-read, and why?",
    label: "reason",
    durMs: null,
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "history.minute",
    kind: "rollup",
    retention: "hot",
    paper: null,
    question:
      "How often does a poll get a cheap delta rather than a full window, and why does it reset?",
    label: "outcome (tail, delta, before, reset.reason)",
    durMs: null,
    n1: "calls",
    n2: "rows_served",
    n3: "bytes_served",
    n4: "total_ms",
    fields: { max_ms: "number" },
    uiIngestable: false,
  },
  {
    name: "history.import.flood",
    kind: "mark",
    retention: "event",
    paper: null,
    question: "How often does a CLI import flood a session, and how much is dropped?",
    label: null,
    durMs: null,
    n1: "local_count",
    n2: "import_count",
    n3: "kept",
    n4: "dropped",
    fields: {},
    uiIngestable: false,
  },
  {
    name: "history.local.drop",
    kind: "mark",
    retention: "event",
    paper: null,
    question: "Did a tab's local history shrink, and what caused it?",
    label: "cause",
    durMs: null,
    n1: "prev_total",
    n2: "now_total",
    n3: "drop",
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  // ── §4.5 Prompts, outbox and admission ──────────────────────────────────────
  {
    name: "ui.outbox.state",
    kind: "transition",
    retention: "event",
    paper: null,
    question:
      "Does every typed prompt reach positive proof, how long does proof take, and how many replay?",
    label: "to_state (queued, attempted, acked, proven, replayed, gave_up)",
    durMs: null,
    n1: "attempts",
    n2: "age_ms",
    n3: null,
    n4: null,
    fields: { from: "enum", proof: "enum" },
    uiIngestable: true,
  },
  {
    name: "ui.prompt.state",
    kind: "transition",
    retention: "event",
    paper: null,
    question:
      "Where do prompts wait, for how long, and does any transition happen that prompt-queue.md forbids?",
    label: "to_state (prompt-queue.md's vocabulary, not restated here)",
    durMs: null,
    n1: "ms_in_from_state",
    n2: null,
    n3: null,
    n4: null,
    fields: { from: "enum", reason: "enum" },
    uiIngestable: true,
  },
  {
    name: "lane.wait",
    kind: "span",
    retention: "hot",
    paper: null,
    question: "How long does work wait for admission, per lane class?",
    label: "lane class (session, global)",
    durMs: "wait",
    n1: "queue_size",
    n2: null,
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "session.state",
    kind: "transition",
    retention: "event",
    paper: null,
    question: "What is each session's gateway-side state history?",
    label: "state",
    durMs: null,
    n1: "queue_depth",
    n2: null,
    n3: null,
    n4: null,
    fields: { from: "enum", reason: "enum" },
    uiIngestable: false,
  },
  // ── §4.6 Turns, tools and delivery ──────────────────────────────────────────
  {
    name: "turn.span",
    kind: "span",
    retention: "hot",
    paper: null,
    question: "Where do the seconds before the model go, per stage, per day?",
    label: "stage (turn-latency.md owns the set)",
    durMs: "stage",
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "hook.span",
    kind: "span",
    retention: "hot",
    paper: null,
    question: "Which plugin inside a narrated stage costs the time?",
    label: "hook:plugin",
    durMs: "handler",
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "run.done",
    kind: "outcome",
    retention: "event",
    paper: null,
    question: "How do turn outcomes and durations move per model and trigger?",
    label: "outcome (completed, aborted, error)",
    durMs: "run",
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    fields: {
      provider: "id",
      model: "id",
      trigger: "enum",
      channel: "enum",
      error_category: "enum",
    },
    uiIngestable: false,
  },
  {
    name: "tool.done",
    kind: "outcome",
    retention: "hot",
    paper: null,
    question:
      "Which tools are slow or failing, independent of any one plugin's hook (observability.md §6 #2)?",
    label: "tool name",
    durMs: "tool call",
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    fields: { outcome: "enum", error_category: "enum" },
    uiIngestable: false,
  },
  {
    name: "exec.done",
    kind: "outcome",
    retention: "event",
    paper: null,
    question: "How often do shell executions fail, time out, or get killed?",
    label: "outcome or failure_kind",
    durMs: "execution",
    n1: "exit_code",
    n2: "command_length",
    n3: null,
    n4: null,
    fields: { target: "enum", mode: "enum", timed_out: "boolean" },
    uiIngestable: false,
  },
  {
    name: "chat.deliver",
    kind: "outcome",
    retention: "event",
    paper: null,
    question: "Did every final reach every client that should see it?",
    label: null,
    durMs: null,
    n1: "attempted",
    n2: "sent",
    n3: "dropped_slow",
    n4: "send_threw",
    fields: { scope_skipped: "number", text_len: "number" },
    uiIngestable: false,
  },
  // ── §4.7 Compaction and eviction ────────────────────────────────────────────
  {
    name: "compaction.decision",
    kind: "outcome",
    retention: "event",
    paper: null,
    question: "Is each gate firing at a sane fill of the REAL window?",
    label: "gate",
    durMs: null,
    n1: "tokens",
    n2: "threshold",
    n3: "window_tokens",
    n4: "fires",
    fields: { over_window: "boolean", source: "enum" },
    uiIngestable: false,
  },
  // The compaction LEDGER (context-window-panel.md §6.1 A4). ONE writer: the A1 owner,
  // src/infra/compaction-telemetry.ts, one row per `end` of every executor (pi-auto, the runner
  // leaf and queued branch, the manual RPC, the EVICT button as trigger "evict", and the claude
  // CLI's own compaction as trigger "cli-internal"). The panel's compactions / evictions / dropped
  // figures read these rows (src/infra/compaction-ledger.ts), never a second row per compaction.
  {
    name: "compaction.run",
    kind: "span",
    retention: "event",
    paper: null,
    question: "What does each compaction cost and save, who ran it, and how often per session?",
    label: "outcome (completed, incomplete)",
    durMs: "compaction",
    n1: "tokens_before",
    n2: "tokens_after",
    n3: "tokens_dropped (measured by the executor, else before minus after)",
    n4: null,
    fields: { trigger: "enum", lane: "enum", provenance: "enum" },
    uiIngestable: false,
  },
  // ENGRAM's pointer-level manifest (J1): what pointer compaction moved out, one level BELOW a
  // compaction.run row. Not a ledger row and not read by the panel's counters; not wired yet.
  {
    name: "context.evict",
    kind: "outcome",
    retention: "event",
    paper: null,
    question: "How much context does pointer eviction remove?",
    label: null,
    durMs: null,
    n1: "evicted_count",
    n2: "evicted_tokens",
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "ui.context.action",
    kind: "outcome",
    retention: "event",
    paper: null,
    question: "Do the panel's buttons do anything, and does the panel's count match the gateway's?",
    label: "action (evict, compact)",
    durMs: null,
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    fields: { result: "enum" },
    uiIngestable: true,
  },
  // ── §4.8 Memory retrieval ───────────────────────────────────────────────────
  {
    name: "recall.pack.refresh",
    kind: "span",
    retention: "hot",
    paper: null,
    question: "What does the ENGRAM pack cost per refresh, and is it growing?",
    label: "path (off_path, cold)",
    durMs: "refresh",
    n1: "events",
    n2: "cc_events",
    n3: "chars",
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "fts.request.minute",
    kind: "rollup",
    retention: "hot",
    paper: null,
    question:
      "How much full-text search runs off the main thread, and how much falls back onto it?",
    label: null,
    durMs: null,
    n1: "requests",
    n2: "worker_ms",
    n3: "fallbacks",
    n4: "disabled",
    fields: {},
    uiIngestable: false,
  },
  {
    name: "fts.fallback",
    kind: "mark",
    retention: "event",
    paper: null,
    question: "Why does the FTS worker fail, and how often?",
    label: "kind (spawn, crash, error, timeout, view, request, backoff, shutdown)",
    durMs: null,
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  // ── §4.9 Worker resources — the per-worker trend series ─────────────────────
  {
    name: "worker.spawn",
    kind: "mark",
    retention: "event",
    paper: null,
    question: "How many workers start, of which type, and how often do they resume?",
    label: "worker_type",
    durMs: null,
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    fields: { resumed: "boolean" },
    uiIngestable: false,
  },
  {
    name: "worker.sample",
    kind: "sample",
    retention: "hot",
    paper: null,
    question:
      "Is any worker type's memory trending up across days, and does a worker grow over its own lifetime?",
    label: "worker_type (gateway, tinker_bridge, fts_thread, whatsmeow, events_writer)",
    durMs: null,
    n1: "mem_bytes",
    n2: "cpu_ms since the last sample",
    n3: "age_ms",
    n4: "peak_bytes",
    fields: {
      source: "enum",
      pids: "number",
      heap_used_bytes: "number",
      heap_limit_bytes: "number",
    },
    uiIngestable: false,
  },
  {
    name: "worker.exit",
    kind: "mark",
    retention: "event",
    paper: null,
    question: "How long do workers live, why do they die, and how big were they at death?",
    label: "exit_class (clean, signal, killed.cause, crash, init_stall)",
    durMs: null,
    n1: "exit_code",
    n2: "lifetime_ms",
    n3: "last_mem_bytes",
    n4: "peak_bytes",
    fields: { signal: "enum", turns_served: "number" },
    uiIngestable: false,
  },
  {
    name: "worker.orphan",
    kind: "mark",
    retention: "event",
    paper: null,
    question:
      "Did a gateway restart leave workers running invisibly beside their re-dispatched twins?",
    label: null,
    durMs: null,
    n1: "age_ms",
    n2: "mem_bytes",
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  // ── §4.10 The observability machinery itself ────────────────────────────────
  {
    name: "instrument.census",
    kind: "sample",
    retention: "hot",
    paper: null,
    question: "How does instrument coverage move over time?",
    label: null,
    durMs: null,
    n1: "declared",
    n2: "live",
    n3: "never",
    n4: "stale",
    fields: { pending: "number", idle: "number", by_config: "number" },
    uiIngestable: false,
  },
  {
    name: "instrument.transition",
    kind: "transition",
    retention: "event",
    paper: null,
    question: "When did each instrument change state, durably across restarts?",
    label: "instrument id",
    durMs: null,
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    // `to` declared 2026-09-25 (§9 step 4). `label` is spent on the instrument id, so the §4 kind
    // convention (label = the new state) leaves the destination verdict with no slot of its own: it
    // has to be a field. With it declared, bridge-diagnostic-bus.ts writes both verdicts and each
    // instrument's FIRST verdict in a process (`to` alone) — the state each boot starts from.
    fields: { from: "enum", to: "enum" },
    uiIngestable: false,
  },
  {
    name: "logs.writer.stats",
    kind: "sample",
    retention: "hot",
    paper: null,
    question: "Is the recorder healthy, and what did it drop and why?",
    label: null,
    durMs: null,
    n1: "written",
    n2: "dropped",
    n3: "queue_depth",
    n4: "max_batch_ms",
    fields: {
      dropped_by_reason: "json",
      unknown_names: "json",
      db_bytes: "number",
      wal_bytes: "number",
    },
    uiIngestable: false,
  },
  {
    name: "logs.retention.run",
    kind: "outcome",
    retention: "event",
    paper: null,
    question:
      "Is retention keeping the database inside its budget, and did it have to shorten a window?",
    label: null,
    durMs: null,
    n1: "rows_deleted",
    n2: "bytes_before",
    n3: "bytes_after",
    n4: null,
    fields: { hot_days: "number", event_days: "number", shortened: "boolean" },
    uiIngestable: false,
  },
  {
    name: "logs.ingest.rejected",
    kind: "mark",
    retention: "event",
    paper: null,
    question: "Is a client sending events the catalog does not declare for it?",
    label: "reason (unknown_name, undeclared_field, not_ingestable, rate_limited, oversize)",
    durMs: null,
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  // ── §4.11 Research records ──────────────────────────────────────────────────
  {
    name: "algo.outcome",
    kind: "outcome",
    retention: "research",
    paper: null,
    question: "How well is each algorithm variant working, with provenance, over months?",
    label: "algorithm/variant",
    durMs: null,
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    fields: {
      outcome: "enum",
      metrics: "json",
      provenance: "json",
      config: "json",
      model: "id",
      provider: "id",
      v: "number",
    },
    uiIngestable: false,
  },
  {
    name: "engram.metric",
    kind: "sample",
    retention: "research",
    paper: null,
    question:
      "What do the ENGRAM phase metrics show, queryable instead of scattered over per-day files?",
    label: "phase/metric_name",
    durMs: null,
    n1: "value",
    n2: null,
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  // ── §4.12 J-series metric events ────────────────────────────────────────────
  {
    name: "j.recall.resolve",
    kind: "outcome",
    retention: "research",
    paper: "J1",
    question:
      "Is pointer compaction lossless in practice — do evicted events come back when asked for?",
    label: "outcome (hit, miss)",
    durMs: null,
    n1: "pointer_age_ms",
    n2: "events_returned",
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "j.fractal.run",
    kind: "outcome",
    retention: "research",
    paper: "J3",
    question: "What is the fractal success rate — the number that sat at zero for eight weeks?",
    label: "outcome (success, docked, failed)",
    durMs: "run",
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "j.cortex.probe",
    kind: "outcome",
    retention: "research",
    paper: "J4",
    question: "Does identity drift across sessions, and does injection correct it?",
    label: "probe id",
    durMs: null,
    n1: "score",
    n2: null,
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "j.consolidation.run",
    kind: "span",
    retention: "research",
    paper: "J5",
    question: "What does each nightly cycle add to and remove from the skill library?",
    label: null,
    durMs: "nightly cycle",
    n1: "events_scanned",
    n2: "skills_extracted",
    n3: "skills_deprecated",
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "j.skill.outcome",
    kind: "outcome",
    retention: "research",
    paper: "J5",
    question: "Are consolidated skills reused, and do they succeed more as nights accumulate?",
    label: "outcome (success, failure)",
    durMs: null,
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    fields: { skill_version: "id" },
    uiIngestable: false,
  },
  {
    name: "j.synapse.debate",
    kind: "span",
    retention: "research",
    paper: "J6",
    question: "Does cross-provider debate change positions, and at what cost?",
    label: null,
    durMs: "debate",
    n1: "participants",
    n2: "providers",
    n3: "rounds",
    n4: "position_changes",
    fields: {},
    uiIngestable: false,
  },
  {
    name: "j.limbic.attempt",
    kind: "outcome",
    retention: "research",
    paper: "J7",
    question: "How often is humor attempted, and at what computed potential?",
    label: "outcome (emitted, suppressed)",
    durMs: null,
    n1: "humor_potential",
    n2: null,
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "j.curiosity.gap",
    kind: "transition",
    retention: "research",
    paper: "J8",
    question: "Are knowledge gaps resolved, and how long do they stay open?",
    label: "to_state (logged, resolved)",
    durMs: null,
    n1: "age_ms",
    n2: null,
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "j.aegis.decision",
    kind: "outcome",
    retention: "research",
    paper: "J9",
    question: "Which security rules fire, and how often are they overridden?",
    label: "rule id",
    durMs: null,
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    fields: { decision: "enum", overridden: "boolean" },
    uiIngestable: false,
  },
  {
    name: "j.amygdala.ask",
    kind: "outcome",
    retention: "research",
    paper: "J11",
    question: "Do the agent's asks reach a human, and how many were false alarms?",
    label: "channel (novelty, incongruity)",
    durMs: null,
    n1: "score",
    n2: null,
    n3: null,
    n4: null,
    fields: { delivered: "boolean", answered: "boolean" },
    uiIngestable: false,
  },
  {
    name: "j.recipe.match",
    kind: "outcome",
    retention: "research",
    paper: "J13",
    question:
      "How often does a prompt find its recipe, and does the rate rise as the library grows?",
    label: "outcome (matched, merged, no_match)",
    durMs: null,
    n1: "score",
    n2: "catalog_size",
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "j.recipe.run",
    kind: "span",
    retention: "research",
    paper: "J13",
    question: "Do recipes complete, and does compounding make later runs cheaper?",
    label: "outcome",
    durMs: "recipe run",
    n1: "steps",
    n2: "failed_steps",
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "j.mnemo.lookup",
    kind: "rollup",
    retention: "research",
    paper: "J14",
    question: "Does concept lookup stay flat as the store grows?",
    label: null,
    durMs: null,
    n1: "lookups",
    n2: "total_ms",
    n3: "index_size",
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "j.mnemo.contradiction",
    kind: "outcome",
    retention: "research",
    paper: "J14",
    question: "How often would a memory write have introduced a contradiction?",
    label: "outcome (pass, flagged, blocked)",
    durMs: null,
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "j.bible.invariants",
    kind: "span",
    retention: "research",
    paper: "J15",
    question: "Is the bible's verify gate green over time, and how fast does red turn green?",
    label: null,
    durMs: "gate run",
    n1: "checks",
    n2: "failed",
    n3: "skipped",
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "j.bound.derived",
    kind: "outcome",
    retention: "research",
    paper: "J16",
    question:
      "Do live-derived bounds kill less near-done work than the frozen constants they replaced?",
    label: "bound name",
    durMs: null,
    n1: "derived_value",
    n2: "ceiling",
    n3: "fired",
    n4: "sample_size",
    fields: {},
    uiIngestable: false,
  },
  {
    name: "j.recipe.parse",
    kind: "outcome",
    retention: "research",
    paper: "J17",
    question: "How many ill-formed recipes does the grammar reject before they run?",
    label: "result (ok, rejected.class)",
    durMs: null,
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  {
    name: "j.route.decision",
    kind: "outcome",
    retention: "research",
    paper: "J19",
    question:
      "Does routing to the measured domain leader improve outcomes enough to pay for itself?",
    label: "domain",
    durMs: null,
    n1: null,
    n2: null,
    n3: null,
    n4: null,
    fields: { house: "id", mode: "enum", score: "number", margin: "number" },
    uiIngestable: false,
  },
  {
    name: "j.orca.lease",
    kind: "outcome",
    retention: "research",
    paper: "J20",
    question: "How often do parallel agents collide on one tree, and what does arbitration cost?",
    label: "outcome (granted, waited, rederived, conflict)",
    durMs: null,
    n1: "wait_ms",
    n2: null,
    n3: null,
    n4: null,
    fields: {},
    uiIngestable: false,
  },
  // catalog rows end
];

const byName = new Map<string, CatalogEvent>(
  EVENT_CATALOG.map((event): [string, CatalogEvent] => [event.name, event]),
);

/**
 * The writer's O(1) emit-path lookup (logging.md §7.5): an undeclared name returns undefined —
 * it is counted and dropped by the writer, never thrown.
 */
export function getCatalogEvent(name: string): CatalogEvent | undefined {
  return byName.get(name);
}
