#!/usr/bin/env node
// shopper.mjs — amazon-shopper CLI. See SKILL.md.

import {
  unlinkSync,
  existsSync,
  readFileSync,
  lstatSync,
  openSync,
  readSync,
  closeSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { resolve, sep } from "node:path";
import { parseArgs } from "node:util";
import { resolveAdapter, DEFAULT_STORE } from "../adapters/registry.mjs";
import { apifyConfigured, searchItems as apifySearch, getItem as apifyGetItem } from "./apify.mjs";
import { categorize } from "./categorize.mjs";
import {
  creatorsApiConfigured,
  searchItems as creatorsSearch,
  getItem as creatorsGetItem,
} from "./creators-api.mjs";
import { rankProducts } from "./rank.mjs";
import { researchProduct } from "./research.mjs";
import { openTaskStore, generateTaskId, STATES } from "./store.mjs";

// Test seam. DATA ONLY, by construction: AMAZON_SHOPPER_TEST_FIXTURES names a
// JSON file mapping a URL substring to a canned response body, which is parsed,
// never executed.
//
// It replaces AMAZON_SHOPPER_FETCH_MODULE (removed in 1.2.0), which import()ed
// whatever path the variable held. ES module initialisation runs top-level code
// immediately, so that variable was arbitrary code execution in the production
// CLI with the full privileges of the shopping process — a "testing only" label
// in the help text is documentation, not a boundary.
function createFixtureFetcher(map) {
  const entries = Object.entries(map);
  return {
    get: async (url) => {
      const hit = entries.find(([pattern]) => url.includes(pattern));
      if (!hit) return { outcome: "BLOCKED", reason: "no-fixture", body: "", finalUrl: url };
      return { outcome: "OK", body: hit[1], finalUrl: url };
    },
    cookiesFor: () => ({}),
  };
}

async function loadFetcher() {
  const fixtures = process.env.AMAZON_SHOPPER_TEST_FIXTURES;
  if (fixtures) return createFixtureFetcher(JSON.parse(readFileSync(fixtures, "utf8")));
  const mod = await import("./fetch.mjs");
  return mod.createFetcher();
}

// Task ids are generated by store.mjs as 12 base64url chars. Anything else is
// refused: a task id is interpolated into a filesystem path, and `close` DELETES
// that path, so an id like "../../../etc/x" would resolve out of the temp dir
// entirely. Validating the id is what keeps the delete inside its sandbox.
const TASK_ID_RE = /^[A-Za-z0-9_-]{6,32}$/;

function assertTaskId(taskId) {
  const id = String(taskId ?? "");
  if (!TASK_ID_RE.test(id)) {
    fail(`invalid task id ${JSON.stringify(id)} — expected 6-32 chars of [A-Za-z0-9_-]`);
  }
  return id;
}

function tmpRoot() {
  return resolve(process.env.AMAZON_SHOPPER_TMPDIR || tmpdir());
}

function tmpDbPath(taskId) {
  return join(tmpRoot(), `amazon-shopper-${assertTaskId(taskId)}.db`);
}

// Delete guard. A path is removed only if ALL of these hold:
//   * it resolves INSIDE the temp root (no traversal, no absolute escape),
//   * it is a regular file and NOT a symlink (lstat, so a link is never followed),
//   * it carries the marker of a file this tool created — the SQLite header for
//     the database, and the matching name prefix for its -wal/-shm siblings.
function safeUnlinkTaskFile(path, { expectSqlite }) {
  const abs = resolve(path);
  const root = tmpRoot();
  if (!abs.startsWith(root + sep)) return { removed: false, reason: "outside temp dir" };
  if (!existsSync(abs)) return { removed: false, reason: "absent" };

  const st = lstatSync(abs);
  if (st.isSymbolicLink()) return { removed: false, reason: "refused: symlink" };
  if (!st.isFile()) return { removed: false, reason: "refused: not a regular file" };

  if (expectSqlite && !hasSqliteHeader(abs)) {
    return { removed: false, reason: "refused: not a SQLite file created by this tool" };
  }
  unlinkSync(abs);
  return { removed: true };
}

function hasSqliteHeader(abs) {
  const MAGIC = "SQLite format 3\0";
  let fd;
  try {
    fd = openSync(abs, "r");
    const buf = Buffer.alloc(16);
    if (readSync(fd, buf, 0, 16, 0) < 16) return false;
    return buf.toString("latin1") === MAGIC;
  } catch {
    return false;
  } finally {
    if (fd !== undefined) closeSync(fd);
  }
}

function emit(obj) {
  process.stdout.write(JSON.stringify(obj) + "\n");
}

function fail(msg, code = 1) {
  process.stderr.write(`ERROR: ${msg}\n`);
  process.exit(code);
}

async function cmdStart(keywords, storeName = DEFAULT_STORE) {
  if (!keywords) fail('usage: amazon-shopper start "<keywords>"');
  let adapter;
  try {
    adapter = resolveAdapter(storeName);
  } catch (e) {
    fail(e.message);
  }
  const taskId = generateTaskId();
  const dbPath = tmpDbPath(taskId);
  const store = openTaskStore(dbPath);
  try {
    store.createTask({ id: taskId, keywords });

    // Data-source priority for Amazon: Apify (paid scraping API) → Creators
    // API (official, gated on 10 sales/30d) → adapter.search HTML fetch
    // (WAF-blocked from this gateway IP; honest exit). Apify/Creators are
    // Amazon-specific official data sources, so they apply only to the amazon
    // store; every other store resolves entirely through adapter.search().
    // See SKILL.md Operational status.
    let products;
    if (adapter.name === "amazon" && apifyConfigured()) {
      try {
        products = await apifySearch(keywords, { maxProducts: 50 });
      } catch (e) {
        store.setTaskFailed(taskId, `apify: ${e.message.slice(0, 200)}`);
        emit({ task_id: taskId, state: "failed", reason: `apify: ${e.message.slice(0, 200)}` });
        return;
      }
    } else if (adapter.name === "amazon" && creatorsApiConfigured()) {
      try {
        products = await creatorsSearch(keywords, { maxProducts: 50 });
      } catch (e) {
        store.setTaskFailed(taskId, `creators-api: ${e.message.slice(0, 200)}`);
        emit({
          task_id: taskId,
          state: "failed",
          reason: `creators-api: ${e.message.slice(0, 200)}`,
        });
        return;
      }
    } else {
      // Search seam → adapter.search(). For amazon this drives the same
      // fetch.mjs HTTP path + extract-search.mjs parse it did inline before;
      // for other stores the adapter owns the fetch + extract entirely.
      const needsFetcher = adapter.name === "amazon";
      const fetcher = needsFetcher ? await loadFetcher() : undefined;
      const r = await adapter.search(keywords, { fetcher });
      if (r.outcome !== "OK") {
        store.setTaskBlocked(taskId, r.reason);
        emit({ task_id: taskId, state: "blocked", reason: r.reason });
        return;
      }
      products = r.products;
    }
    if (products.length === 0) {
      store.setTaskState(taskId, STATES.COMPLETE);
      emit({ task_id: taskId, state: "complete", products_count: 0, top_3: [], skipped: [] });
      return;
    }
    store.insertProducts(taskId, products);

    const cat = await categorize(products);
    for (const q of cat.qualifying_questions) {
      store.insertPendingQuestion(taskId, q);
    }
    store.setTaskState(taskId, STATES.AWAITING_QUESTIONS);

    emit({
      task_id: taskId,
      state: "awaiting_questions",
      products_count: products.length,
      pending_questions: store.pendingQuestions().map((q) => ({
        id: q.id,
        text: q.text,
        options: q.options,
        why_load_bearing: q.why_load_bearing,
      })),
    });
  } finally {
    store.close();
  }
}

async function cmdAnswer(taskId, qId, answer) {
  if (!taskId || !qId || answer === undefined || answer === "")
    fail('usage: amazon-shopper answer <task-id> <q-id> "<answer>"');
  const store = openTaskStore(tmpDbPath(taskId));
  try {
    const task = store.getTask(taskId);
    if (!task) fail(`task ${taskId} not found`);
    if (task.state !== STATES.AWAITING_QUESTIONS)
      fail(`task is in state ${task.state}, not awaiting_questions`);
    store.recordAnswer(taskId, qId, answer);
    const pending = store.pendingQuestions();
    if (pending.length === 0) {
      store.setTaskState(taskId, STATES.RANKING);
      emit({ state: "ready_to_rank" });
    } else {
      emit({
        state: "awaiting_questions",
        next_question: { id: pending[0].id, text: pending[0].text, options: pending[0].options },
      });
    }
  } finally {
    store.close();
  }
}

async function cmdRank(taskId, storeName = DEFAULT_STORE) {
  if (!taskId) fail("usage: amazon-shopper rank <task-id>");
  let adapter;
  try {
    adapter = resolveAdapter(storeName);
  } catch (e) {
    fail(e.message);
  }
  const store = openTaskStore(tmpDbPath(taskId));
  try {
    const task = store.getTask(taskId);
    if (!task) fail(`task ${taskId} not found`);
    if (task.state !== STATES.RANKING) fail(`task is in state ${task.state}, not ranking`);

    const products = store.listProducts();
    // Build category_filter ONLY from FORM-related answers — those are real
    // catalog filters (liquid vs granular). Other answers like "direction"
    // or "pool_size" are user preferences captured in volume_bracket but
    // should not gate matchesCategory (where they'd reject everything).
    const allAnswers = store.listAnswers(taskId);
    const category_filter = {};
    for (const [key, value] of Object.entries(allAnswers)) {
      if (/form/i.test(key) || /direction/i.test(key)) category_filter[key] = value;
    }
    const volume_bracket =
      allAnswers.volume || allAnswers.pool_volume || allAnswers.form_and_size || null;

    const isAmazon = adapter.name === "amazon";
    const topK = products.slice(0, 10);
    // Apify/Creators are Amazon-specific official detail sources.
    const useApify = isAmazon && apifyConfigured();
    const useCreators = isAmazon && !useApify && creatorsApiConfigured();
    const useApi = useApify || useCreators;
    // Amazon's detailFetch needs the polite fetch.mjs client injected; other
    // adapters own their own transport.
    const fetcher = useApi || !isAmazon ? null : await loadFetcher();
    const SEM = 4;
    const queue = [...topK];
    async function worker() {
      while (queue.length) {
        const p = queue.shift();
        try {
          let detailSpec;
          if (useApify) {
            detailSpec = await apifyGetItem(p.asin);
          } else if (useCreators) {
            detailSpec = await creatorsGetItem(p.asin);
          } else {
            // Detail seam → adapter.detailFetch(). Returns the OK/BLOCKED
            // envelope; on block we fall back to a title-only spec and log the
            // ladder, exactly as the inline Amazon path did before.
            const r = await adapter.detailFetch(p, { fetcher });
            if (r && r.outcome === "OK") {
              detailSpec = r.detailSpec;
            } else {
              detailSpec = { combined_text: p.title || "" };
              store.logLadder(p.id, adapter.name, "blocked", p.url, r?.reason ?? "no-detail");
            }
          }
          const research = await researchProduct({
            product: p,
            detailSpec,
            fetcher,
            logger: (prod, step, outcome, url, notes) =>
              store.logLadder(prod.id, step, outcome, url, notes),
          });
          store.updateProductDetail(p.asin, { ...research });
        } catch (e) {
          const src = useApify ? "apify" : useCreators ? "creators-api" : adapter.name;
          store.logLadder(p.id, src, "error", p.url, e.message);
        }
      }
    }
    await Promise.all(Array.from({ length: SEM }, () => worker()));

    const refreshed = store.listProducts();
    const result = await rankProducts({ products: refreshed, category_filter, volume_bracket });
    store.setTaskState(taskId, STATES.COMPLETE);
    emit({ task_id: taskId, state: "complete", ...result });
  } finally {
    store.close();
  }
}

// set-spec — inject a confirmed concentration/ingredient for one product,
// recompute active_kg, and persist. This is the write-back seam for the
// parallel brand-research subagent flow (see SKILL.md → "Brand-concentration
// research"): when `rank` returns needs_concentration_research, the agent spins
// a subagent per brand to find the real concentration online, then calls this
// for each ASIN and re-runs `rank`.
async function cmdSetSpec(taskId, asin, opts) {
  if (!taskId || !asin)
    fail(
      "usage: amazon-shopper set-spec <task-id> <asin> --concentration <pct> [--ingredient <name>] [--source <url>]",
    );
  const { activeKg, parseSpecFromTitle } = await import("./title-spec.mjs");
  const store = openTaskStore(tmpDbPath(taskId));
  try {
    const task = store.getTask(taskId);
    if (!task) fail(`task ${taskId} not found`);
    const p = store.getProductByAsin(asin);
    if (!p) fail(`product ${asin} not found in task ${taskId}`);
    const concentration_pct =
      opts.concentration != null ? Number(opts.concentration) : p.concentration_pct;
    if (!Number.isFinite(concentration_pct)) fail("--concentration must be a number (0-100)");
    // Backfill package size / form from the title when the product was never
    // researched (e.g. outside the rank top-10) — otherwise active_kg can't be
    // computed even with a confirmed concentration.
    const ts = parseSpecFromTitle(p.title || "");
    const merged = {
      active_ingredient: opts.ingredient ?? p.active_ingredient ?? ts.active_ingredient ?? null,
      concentration_pct,
      package_size_kg: p.package_size_kg ?? ts.package_size_kg ?? null,
      package_size_l: p.package_size_l ?? ts.package_size_l ?? null,
      form: p.form ?? ts.form ?? null,
    };
    const detail = {
      ...merged,
      active_kg: activeKg(merged),
      spec_status: "ok",
      spec_source: opts.source ? `subagent:${opts.source}` : "subagent",
    };
    store.updateProductDetail(asin, detail);
    store.logLadder(p.id, "subagent", "ok", opts.source ?? null, `conc=${concentration_pct}%`);
    emit({
      ok: true,
      task_id: taskId,
      asin,
      concentration_pct,
      active_kg: detail.active_kg,
      spec_source: detail.spec_source,
    });
  } finally {
    store.close();
  }
}

async function cmdInspect(taskId, productAsin) {
  if (!taskId) fail("usage: amazon-shopper inspect <task-id> [--product <asin>]");
  const store = openTaskStore(tmpDbPath(taskId));
  try {
    const task = store.getTask(taskId);
    if (!task) fail(`task ${taskId} not found`);
    if (productAsin) {
      emit({ task, product: store.getProductByAsin(productAsin) });
    } else {
      emit({ task, products: store.listProducts(), pending_questions: store.pendingQuestions() });
    }
  } finally {
    store.close();
  }
}

function cmdClose(taskId) {
  if (!taskId) fail("usage: amazon-shopper close <task-id>");
  const id = assertTaskId(taskId);
  const dbPath = tmpDbPath(id);
  const removed = [];
  const refused = [];

  const main = safeUnlinkTaskFile(dbPath, { expectSqlite: true });
  main.removed
    ? removed.push(dbPath)
    : main.reason !== "absent" && refused.push(`${dbPath}: ${main.reason}`);

  // The -wal/-shm siblings are SQLite's own journals: same directory, same
  // validated name, but they carry no SQLite header of their own.
  for (const ext of ["-wal", "-shm"]) {
    const p = dbPath + ext;
    const r = safeUnlinkTaskFile(p, { expectSqlite: false });
    r.removed ? removed.push(p) : r.reason !== "absent" && refused.push(`${p}: ${r.reason}`);
  }

  emit({ ok: true, task_id: id, closed: true, removed, ...(refused.length ? { refused } : {}) });
}

const HELP = `\
amazon-shopper — opinionated Amazon.es shopping skill (HTML-only)

USAGE:
  amazon-shopper start "<keywords>" [--store <name>]
  amazon-shopper answer <task-id> <q-id> "<answer>"
  amazon-shopper rank <task-id> [--store <name>]
  amazon-shopper inspect <task-id> [--product <asin>]
  amazon-shopper set-spec <task-id> <asin> --concentration <pct> [--ingredient <name>] [--source <url>]
  amazon-shopper close <task-id>

STORES (--store, default: amazon):
  amazon       Amazon.es (Apify → Creators API → HTML; default).
  milanuncios  Milanuncios classifieds (HTML __INITIAL_PROPS__ parse).
  wallapop     Wallapop (stub — 403-gated, needs browser-relay).

ENV:
  AMAZON_SHOPPER_TMPDIR        Override /tmp location for the per-task SQLite.
  AMAZON_SHOPPER_TEST_FIXTURES JSON map of url-substring -> canned body (tests only; data, not code).
  MOCK_LLM_RESPONSE_FILE       Path to a JSON file of mocked LLM responses (testing only).
  AMAZON_SHOPPER_LLM_CMD       Subprocess CLI for LLM calls (allowlisted; default: claude --print).
  AMAZON_SHOPPER_ALLOW_WEB_RESEARCH=1   Opt in to the off-Amazon spec-research rungs (default: off).
  AMAZON_SHOPPER_ENABLE_OTHER_STORES=1  Opt in to the non-Amazon store adapters (default: off).

See SKILL.md.
`;

async function main() {
  const [sub, ...rest] = process.argv.slice(2);
  if (!sub || sub === "--help" || sub === "-h") {
    process.stdout.write(HELP);
    return;
  }
  switch (sub) {
    case "start": {
      const { values, positionals } = parseArgs({
        args: rest,
        options: { store: { type: "string" } },
        allowPositionals: true,
        strict: false,
      });
      return cmdStart(positionals[0], values.store || DEFAULT_STORE);
    }
    case "answer":
      return cmdAnswer(rest[0], rest[1], rest.slice(2).join(" "));
    case "rank": {
      const { values, positionals } = parseArgs({
        args: rest,
        options: { store: { type: "string" } },
        allowPositionals: true,
        strict: false,
      });
      return cmdRank(positionals[0], values.store || DEFAULT_STORE);
    }
    case "inspect": {
      const { values, positionals } = parseArgs({
        args: rest,
        options: { product: { type: "string" } },
        allowPositionals: true,
        strict: false,
      });
      return cmdInspect(positionals[0], values.product);
    }
    case "set-spec": {
      const { values, positionals } = parseArgs({
        args: rest,
        options: {
          concentration: { type: "string" },
          ingredient: { type: "string" },
          source: { type: "string" },
        },
        allowPositionals: true,
        strict: false,
      });
      return cmdSetSpec(positionals[0], positionals[1], values);
    }
    case "close":
      return cmdClose(rest[0]);
    default:
      fail(`unknown subcommand: ${sub}`);
  }
}

main().catch((e) => {
  process.stderr.write(`FATAL: ${e.stack || e.message}\n`);
  process.exit(1);
});
