// tinker-ui/src/panels/aa-effort-estimate.ts
// GENERATED by model-rank-refresh/scripts/estimate_effort_index.py — do not hand-edit.
// Retrieved: 2026-09-03T04:13:28+00:00
//
// ESTIMATED Artificial Analysis Intelligence Index for (family, effort) cells AA did
// not publish. the architect 2026-09-02: approximate from other measurements, as long as the
// chart never confuses an estimate with a measurement. Two methods, both named on
// every cell:
//   benchmark-fit — R²-weighted mean of per-benchmark linear fits AA ~ a + b·score,
//                   fitted on cells AA DID score at that effort; basis lists the
//                   benchmarks that ran this model at this effort (Epoch AI hub,
//                   LMArena text Elo).
//   ladder-shape  — the model's nearest AA-measured rung × the mean AA ratio
//                   between those two efforts over AA's own multi-rung families.
//                   Assumes an average ladder shape; sd is the spread of those ratios.
//   blend         — both, inverse-variance weighted.
// Every estimate is clamped between the model's measured neighbours and kept
// non-decreasing across efforts (pool-adjacent-violators), because a ladder
// whose 'high' outscores its measured 'max' is noise, not a finding.
// A cell AA measured is NEVER here — aa-effort-index.ts wins.
//
// Fits kept (n ≥ 6, R² ≥ 0.55):
//   FrontierMath-2025-02-28-Private: n=16 R²=0.90 rmse=4.2
//   GSO-Bench: n=6 R²=0.90 rmse=4.6
//   ARC-AGI: n=67 R²=0.89 rmse=4.6
//   APEX-Agents: n=13 R²=0.88 rmse=3.4
//   LMArena text Elo: n=15 R²=0.87 rmse=5.7
//   DeepSWE: n=46 R²=0.86 rmse=2.3
//   FrontierMath-Tier-4-2025-07-01-Private: n=16 R²=0.83 rmse=5.3
//   LMCA: n=36 R²=0.82 rmse=5.7
//   DTBench: n=36 R²=0.82 rmse=5.7
//   VPCT: n=8 R²=0.82 rmse=3.4
//   FrontierMath-Tiers-1-3-v2-Private: n=38 R²=0.81 rmse=6.7
//   SWE-Bench verified: n=9 R²=0.81 rmse=4.2
//   ARC-AGI-2: n=66 R²=0.80 rmse=6.2
//   OSWorld 2.0: n=10 R²=0.75 rmse=2.2
//   GPQA diamond: n=52 R²=0.71 rmse=8.1
//   SimpleBench: n=9 R²=0.70 rmse=8.5
//   OTIS Mock AIME 2024-2025: n=53 R²=0.65 rmse=9.0
//   Mystery Game Puzzles: n=46 R²=0.63 rmse=9.3
//   WeirdML: n=33 R²=0.60 rmse=9.0
//   Aider polyglot: n=6 R²=0.57 rmse=4.5
//   SimpleQA Verified: n=33 R²=0.57 rmse=8.2
//   CritPt: n=67 R²=0.56 rmse=7.2

import type { AaEffort } from "./aa-effort-index.js";

export interface AaEstimate {
  /** Estimated AA Intelligence Index. */
  v: number;
  /** Spread of the estimate, AA points. */
  sd: number;
  method: "benchmark-fit" | "ladder-shape" | "blend";
  /** Benchmarks (or the AA-ladder delta) the number rests on. */
  basis: string[];
}

export const AA_EFFORT_ESTIMATE: Record<string, Partial<Record<AaEffort, AaEstimate>>> = {
  "claude-fable-5": {
    low: {
      v: 49.59,
      sd: 4.36,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DeepSWE",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "max\u2192low ratio over 6 AA ladders",
      ],
    },
    medium: {
      v: 55.49,
      sd: 3.31,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "DeepSWE", "max\u2192medium ratio over 5 AA ladders"],
    },
    high: {
      v: 57.94,
      sd: 1.89,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DeepSWE",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
        "max\u2192high ratio over 7 AA ladders",
      ],
    },
    xhigh: {
      v: 60.19,
      sd: 1.21,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DeepSWE",
        "SimpleQA Verified",
        "max\u2192xhigh ratio over 6 AA ladders",
      ],
    },
  },
  "claude-fable-5-1": {
    minimal: {
      v: 32.15,
      sd: 8.46,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "claude-opus-4-5": {
    high: { v: 47.48, sd: 5.68, method: "benchmark-fit", basis: ["DTBench", "LMCA"] },
  },
  "claude-opus-4-6-adaptive": {
    low: {
      v: 34.8,
      sd: 3.3,
      method: "blend",
      basis: ["Mystery Game Puzzles", "max\u2192low ratio over 6 AA ladders"],
    },
    medium: {
      v: 38.94,
      sd: 3.23,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 5 AA ladders"],
    },
    high: {
      v: 42.55,
      sd: 1.38,
      method: "blend",
      basis: ["GSO-Bench", "WeirdML", "max\u2192high ratio over 7 AA ladders"],
    },
    xhigh: {
      v: 43.55,
      sd: 0.9,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 6 AA ladders"],
    },
  },
  "claude-opus-4-7": {
    low: {
      v: 47.23,
      sd: 3.42,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "max\u2192low ratio over 6 AA ladders"],
    },
    medium: {
      v: 50.06,
      sd: 3.19,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "max\u2192medium ratio over 5 AA ladders"],
    },
    high: {
      v: 51.69,
      sd: 1.67,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GSO-Bench",
        "WeirdML",
        "max\u2192high ratio over 7 AA ladders",
      ],
    },
    xhigh: {
      v: 53.2,
      sd: 1.09,
      method: "blend",
      basis: [
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "max\u2192xhigh ratio over 6 AA ladders",
      ],
    },
  },
  "claude-opus-4-8": {
    low: {
      v: 47.05,
      sd: 3.74,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DeepSWE",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "max\u2192low ratio over 6 AA ladders",
      ],
    },
    medium: {
      v: 51.03,
      sd: 3.4,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DeepSWE",
        "WeirdML",
        "max\u2192medium ratio over 5 AA ladders",
      ],
    },
    high: {
      v: 53.72,
      sd: 1.68,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "DeepSWE", "max\u2192high ratio over 7 AA ladders"],
    },
    xhigh: {
      v: 55.51,
      sd: 1.13,
      method: "blend",
      basis: [
        "DeepSWE",
        "Mystery Game Puzzles",
        "WeirdML",
        "max\u2192xhigh ratio over 6 AA ladders",
      ],
    },
  },
  "claude-opus-5": {
    minimal: {
      v: 31.17,
      sd: 8.2,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "claude-sonnet-4-6-adaptive": {
    low: {
      v: 37.99,
      sd: 3.52,
      method: "blend",
      basis: ["Mystery Game Puzzles", "max\u2192low ratio over 6 AA ladders"],
    },
    medium: {
      v: 42.37,
      sd: 3.22,
      method: "blend",
      basis: [
        "GPQA diamond",
        "OSWorld 2.0",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
        "max\u2192medium ratio over 5 AA ladders",
      ],
    },
    high: {
      v: 45.2,
      sd: 1.48,
      method: "blend",
      basis: [
        "APEX-Agents",
        "ARC-AGI",
        "ARC-AGI-2",
        "DeepSWE",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "max\u2192high ratio over 7 AA ladders",
      ],
    },
    xhigh: {
      v: 46.88,
      sd: 0.97,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 6 AA ladders"],
    },
  },
  "claude-sonnet-5": {
    low: {
      v: 44.84,
      sd: 2.06,
      method: "blend",
      basis: ["DeepSWE", "max\u2192low ratio over 6 AA ladders"],
    },
    medium: {
      v: 48.27,
      sd: 2.02,
      method: "blend",
      basis: ["DeepSWE", "max\u2192medium ratio over 5 AA ladders"],
    },
    high: {
      v: 51.45,
      sd: 1.69,
      method: "blend",
      basis: ["CritPt", "DeepSWE", "WeirdML", "max\u2192high ratio over 7 AA ladders"],
    },
    xhigh: {
      v: 53.48,
      sd: 1.09,
      method: "blend",
      basis: [
        "DeepSWE",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "max\u2192xhigh ratio over 6 AA ladders",
      ],
    },
  },
  "deepseek-v4-flash": {
    low: {
      v: 43.37,
      sd: 3.38,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "max\u2192low ratio over 6 AA ladders"],
    },
    medium: {
      v: 44.86,
      sd: 3.72,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 5 AA ladders"],
    },
    high: {
      v: 48.32,
      sd: 1.59,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "CritPt", "WeirdML", "max\u2192high ratio over 7 AA ladders"],
    },
    xhigh: {
      v: 50.18,
      sd: 1.03,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 6 AA ladders"],
    },
  },
  "deepseek-v4-flash-0420": {
    minimal: {
      v: 20.69,
      sd: 4.25,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 32.63,
      sd: 4.06,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 16 AA ladders"],
    },
    medium: {
      v: 37.33,
      sd: 3.13,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 16 AA ladders"],
    },
    xhigh: {
      v: 40.23,
      sd: 0.94,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
  },
  "deepseek-v4-flash-vision": {
    low: {
      v: 40.63,
      sd: 4.05,
      method: "ladder-shape",
      basis: ["max\u2192low ratio over 6 AA ladders"],
    },
    medium: {
      v: 44.61,
      sd: 3.7,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 5 AA ladders"],
    },
    high: {
      v: 48.12,
      sd: 1.6,
      method: "ladder-shape",
      basis: ["max\u2192high ratio over 7 AA ladders"],
    },
    xhigh: {
      v: 49.89,
      sd: 1.03,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 6 AA ladders"],
    },
  },
  "deepseek-v4-pro": {
    low: {
      v: 45.49,
      sd: 3.41,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "max\u2192low ratio over 6 AA ladders"],
    },
    medium: {
      v: 46.1,
      sd: 3.82,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 5 AA ladders"],
    },
    high: {
      v: 49.69,
      sd: 1.63,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "CritPt",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
        "max\u2192high ratio over 7 AA ladders",
      ],
    },
    xhigh: {
      v: 51.56,
      sd: 1.06,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 6 AA ladders"],
    },
  },
  "deepseek-v4-pro-0424": {
    minimal: {
      v: 23.2,
      sd: 4.77,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 36.58,
      sd: 4.56,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 16 AA ladders"],
    },
    medium: {
      v: 41.85,
      sd: 3.51,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 16 AA ladders"],
    },
    xhigh: {
      v: 45.11,
      sd: 1.05,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
  },
  "gemini-3-1-flash-lite": {
    minimal: {
      v: 21.19,
      sd: 12.89,
      method: "benchmark-fit",
      basis: ["FrontierMath-Tiers-1-3-v2-Private", "GPQA diamond", "OTIS Mock AIME 2024-2025"],
    },
    low: {
      v: 23.17,
      sd: 11.36,
      method: "benchmark-fit",
      basis: ["FrontierMath-Tiers-1-3-v2-Private", "GPQA diamond", "OTIS Mock AIME 2024-2025"],
    },
    high: {
      v: 34.76,
      sd: 8.65,
      method: "benchmark-fit",
      basis: [
        "DTBench",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "LMCA",
        "OTIS Mock AIME 2024-2025",
      ],
    },
  },
  "gemini-3-1-pro": {
    low: { v: 46.54, sd: 9.28, method: "benchmark-fit", basis: ["Mystery Game Puzzles"] },
    medium: { v: 48.77, sd: 9.28, method: "benchmark-fit", basis: ["Mystery Game Puzzles"] },
    high: {
      v: 55.47,
      sd: 8.98,
      method: "benchmark-fit",
      basis: [
        "DTBench",
        "GPQA diamond",
        "LMCA",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
      ],
    },
  },
  "gemini-3-5-flash": {
    low: {
      v: 42.34,
      sd: 3.19,
      method: "blend",
      basis: [
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "medium\u2192low ratio over 16 AA ladders",
      ],
    },
    xhigh: {
      v: 53.58,
      sd: 1.25,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 55.65,
      sd: 1.88,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gemini-3-5-flash-lite": {
    minimal: {
      v: 20.37,
      sd: 3.84,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "high\u2192minimal ratio over 4 AA ladders",
      ],
    },
    low: {
      v: 30.9,
      sd: 3.66,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "high\u2192low ratio over 16 AA ladders",
      ],
    },
    medium: {
      v: 34.24,
      sd: 2.68,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "high\u2192medium ratio over 16 AA ladders"],
    },
    xhigh: {
      v: 38.6,
      sd: 0.9,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 40.09,
      sd: 1.35,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gemini-3-6-flash": {
    minimal: {
      v: 29.23,
      sd: 4.97,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "high\u2192minimal ratio over 4 AA ladders",
      ],
    },
    low: {
      v: 43.23,
      sd: 4.46,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "high\u2192low ratio over 16 AA ladders",
      ],
    },
    medium: {
      v: 49.4,
      sd: 3.34,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "high\u2192medium ratio over 16 AA ladders"],
    },
    xhigh: {
      v: 53.18,
      sd: 1.24,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 55.24,
      sd: 1.86,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gemini-3-7-flash": {
    minimal: {
      v: 28.4,
      sd: 7.47,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    xhigh: {
      v: 57.77,
      sd: 1.35,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 60.0,
      sd: 2.02,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gemini-3-8-flash": {
    minimal: {
      v: 30.11,
      sd: 7.92,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    xhigh: {
      v: 60.5,
      sd: 1.41,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 62.84,
      sd: 2.12,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gemini-3-flash": {
    minimal: { v: 43.58, sd: 9.28, method: "benchmark-fit", basis: ["Mystery Game Puzzles"] },
    low: { v: 44.32, sd: 9.28, method: "benchmark-fit", basis: ["Mystery Game Puzzles"] },
    high: {
      v: 48.63,
      sd: 9.87,
      method: "benchmark-fit",
      basis: [
        "DTBench",
        "GPQA diamond",
        "LMCA",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
      ],
    },
  },
  "gemini-3-flash-thinking": {
    minimal: { v: 48.87, sd: 5.74, method: "benchmark-fit", basis: ["LMArena text Elo"] },
  },
  "gemini-3-pro": {
    minimal: {
      v: 21.54,
      sd: 4.43,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    medium: {
      v: 38.22,
      sd: 3.68,
      method: "ladder-shape",
      basis: ["low\u2192medium ratio over 16 AA ladders"],
    },
    xhigh: {
      v: 41.87,
      sd: 0.98,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 43.49,
      sd: 1.47,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gemma-4-26b-a4b-it": {
    minimal: {
      v: 35.46,
      sd: 10.04,
      method: "benchmark-fit",
      basis: ["GPQA diamond", "OTIS Mock AIME 2024-2025"],
    },
  },
  "gemma-4-31b-it": {
    minimal: {
      v: 33.61,
      sd: 8.57,
      method: "benchmark-fit",
      basis: ["GPQA diamond", "OTIS Mock AIME 2024-2025"],
    },
  },
  "glm-5-2": {
    minimal: { v: 38.4, sd: 9.28, method: "benchmark-fit", basis: ["Mystery Game Puzzles"] },
    low: {
      v: 41.59,
      sd: 3.78,
      method: "blend",
      basis: [
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "max\u2192low ratio over 6 AA ladders",
      ],
    },
    medium: {
      v: 44.28,
      sd: 3.5,
      method: "blend",
      basis: ["Mystery Game Puzzles", "max\u2192medium ratio over 5 AA ladders"],
    },
    high: {
      v: 49.06,
      sd: 1.58,
      method: "blend",
      basis: ["DeepSWE", "WeirdML", "max\u2192high ratio over 7 AA ladders"],
    },
    xhigh: {
      v: 51.02,
      sd: 1.05,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 6 AA ladders"],
    },
  },
  "glm-5-3": {
    low: {
      v: 46.97,
      sd: 4.68,
      method: "ladder-shape",
      basis: ["max\u2192low ratio over 6 AA ladders"],
    },
    medium: {
      v: 51.58,
      sd: 4.27,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 5 AA ladders"],
    },
    high: {
      v: 55.63,
      sd: 1.85,
      method: "ladder-shape",
      basis: ["max\u2192high ratio over 7 AA ladders"],
    },
    xhigh: {
      v: 57.68,
      sd: 1.19,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 6 AA ladders"],
    },
  },
  "glm-5-3-flash": {
    low: {
      v: 45.35,
      sd: 4.52,
      method: "ladder-shape",
      basis: ["max\u2192low ratio over 6 AA ladders"],
    },
    medium: {
      v: 49.8,
      sd: 4.13,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 5 AA ladders"],
    },
    high: {
      v: 53.71,
      sd: 1.79,
      method: "ladder-shape",
      basis: ["max\u2192high ratio over 7 AA ladders"],
    },
    xhigh: {
      v: 55.69,
      sd: 1.15,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 6 AA ladders"],
    },
  },
  "gpt-5": {
    xhigh: {
      v: 36.41,
      sd: 0.85,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 37.82,
      sd: 1.28,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-1": {
    minimal: {
      v: 19.87,
      sd: 4.08,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 30.83,
      sd: 3.53,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "high\u2192low ratio over 16 AA ladders",
      ],
    },
    medium: {
      v: 35.76,
      sd: 2.83,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "VPCT",
        "high\u2192medium ratio over 16 AA ladders",
      ],
    },
    xhigh: {
      v: 38.63,
      sd: 0.9,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 40.12,
      sd: 1.35,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-1-codex": {
    minimal: {
      v: 18.88,
      sd: 3.88,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 29.77,
      sd: 3.71,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 16 AA ladders"],
    },
    medium: {
      v: 34.06,
      sd: 2.85,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 16 AA ladders"],
    },
    xhigh: {
      v: 36.7,
      sd: 0.86,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 38.12,
      sd: 1.29,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-1-codex-mini": {
    minimal: {
      v: 16.62,
      sd: 3.42,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 26.2,
      sd: 3.26,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 16 AA ladders"],
    },
    medium: {
      v: 29.98,
      sd: 2.51,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 16 AA ladders"],
    },
    xhigh: {
      v: 32.31,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 33.56,
      sd: 1.13,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-2": {
    minimal: {
      v: 20.7,
      sd: 5.45,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 34.82,
      sd: 2.69,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "WeirdML",
        "medium\u2192low ratio over 16 AA ladders",
      ],
    },
    high: {
      v: 41.4,
      sd: 2.8,
      method: "blend",
      basis: [
        "APEX-Agents",
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "GPQA diamond",
        "GSO-Bench",
        "LMArena text Elo",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SWE-Bench verified",
        "SimpleBench",
        "SimpleQA Verified",
        "VPCT",
        "medium\u2192high ratio over 16 AA ladders",
      ],
    },
    max: {
      v: 44.74,
      sd: 0.94,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 6 AA ladders"],
    },
  },
  "gpt-5-2-codex": {
    low: {
      v: 33.37,
      sd: 2.59,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 9 AA ladders"],
    },
    medium: {
      v: 36.14,
      sd: 3.1,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 11 AA ladders"],
    },
    high: {
      v: 40.0,
      sd: 0.95,
      method: "ladder-shape",
      basis: ["xhigh\u2192high ratio over 7 AA ladders"],
    },
    max: {
      v: 42.54,
      sd: 0.89,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 6 AA ladders"],
    },
  },
  "gpt-5-2-pro": {
    medium: { v: 46.81, sd: 6.4, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    high: { v: 50.84, sd: 5.64, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    xhigh: {
      v: 55.2,
      sd: 5.76,
      method: "benchmark-fit",
      basis: ["ARC-AGI", "FrontierMath-Tiers-1-3-v2-Private"],
    },
  },
  "gpt-5-3-codex": {
    low: {
      v: 36.85,
      sd: 2.86,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 9 AA ladders"],
    },
    medium: {
      v: 39.91,
      sd: 3.42,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 11 AA ladders"],
    },
    high: {
      v: 44.21,
      sd: 1.01,
      method: "blend",
      basis: ["SWE-Bench verified", "xhigh\u2192high ratio over 7 AA ladders"],
    },
    max: {
      v: 46.98,
      sd: 0.98,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 6 AA ladders"],
    },
  },
  "gpt-5-4": {
    medium: {
      v: 46.38,
      sd: 3.81,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "low\u2192medium ratio over 16 AA ladders",
      ],
    },
    high: {
      v: 51.53,
      sd: 1.2,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "GSO-Bench",
        "OTIS Mock AIME 2024-2025",
        "SWE-Bench verified",
        "xhigh\u2192high ratio over 7 AA ladders",
      ],
    },
    max: {
      v: 54.83,
      sd: 1.15,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 6 AA ladders"],
    },
  },
  "gpt-5-4-mini": {
    minimal: {
      v: 16.2,
      sd: 4.26,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 27.1,
      sd: 2.17,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tiers-1-3-v2-Private",
        "Mystery Game Puzzles",
        "medium\u2192low ratio over 16 AA ladders",
      ],
    },
    high: {
      v: 32.4,
      sd: 2.3,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "GPQA diamond",
        "LMArena text Elo",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "WeirdML",
        "medium\u2192high ratio over 16 AA ladders",
      ],
    },
    max: {
      v: 42.26,
      sd: 0.88,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 6 AA ladders"],
    },
  },
  "gpt-5-4-nano": {
    minimal: {
      v: 16.4,
      sd: 4.31,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 27.45,
      sd: 2.18,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "medium\u2192low ratio over 16 AA ladders",
      ],
    },
    high: {
      v: 32.47,
      sd: 2.31,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "LMArena text Elo",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "WeirdML",
        "medium\u2192high ratio over 16 AA ladders",
      ],
    },
    max: {
      v: 40.99,
      sd: 0.86,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 6 AA ladders"],
    },
  },
  "gpt-5-4-pro": {
    xhigh: {
      v: 57.06,
      sd: 7.53,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "CritPt",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "SimpleQA Verified",
      ],
    },
  },
  "gpt-5-5": {
    minimal: {
      v: 27.34,
      sd: 7.19,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    max: {
      v: 58.12,
      sd: 1.21,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 6 AA ladders"],
    },
  },
  "gpt-5-5-pro": {
    high: {
      v: 59.84,
      sd: 6.88,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "SimpleBench",
        "pooled for ladder order",
      ],
    },
    xhigh: {
      v: 59.84,
      sd: 7.5,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "CritPt",
        "DTBench",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "LMCA",
        "OTIS Mock AIME 2024-2025",
        "pooled for ladder order",
      ],
    },
  },
  "gpt-5-6-luna": {
    minimal: {
      v: 20.68,
      sd: 5.44,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "gpt-5-6-sol": {
    minimal: {
      v: 29.54,
      sd: 7.77,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "gpt-5-6-terra": {
    minimal: {
      v: 24.86,
      sd: 6.54,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "gpt-5-codex": {
    minimal: {
      v: 19.65,
      sd: 4.04,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 30.97,
      sd: 3.86,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 16 AA ladders"],
    },
    medium: {
      v: 35.43,
      sd: 2.97,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 16 AA ladders"],
    },
    xhigh: {
      v: 38.19,
      sd: 0.89,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 39.66,
      sd: 1.34,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-mini": {
    low: {
      v: 25.8,
      sd: 2.18,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tiers-1-3-v2-Private",
        "medium\u2192low ratio over 16 AA ladders",
        "clamped to measured neighbours",
      ],
    },
    xhigh: {
      v: 31.63,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders", "clamped to measured neighbours"],
    },
    max: {
      v: 31.63,
      sd: 0.93,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders", "clamped to measured neighbours"],
    },
  },
  "gpt-5-nano": {
    low: {
      v: 17.21,
      sd: 1.4,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
        "medium\u2192low ratio over 16 AA ladders",
      ],
    },
    xhigh: {
      v: 20.77,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 21.57,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-pro": {
    high: {
      v: 44.09,
      sd: 8.1,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "SimpleBench",
        "WeirdML",
      ],
    },
  },
  "gpt-oss-120b": {
    minimal: {
      v: 12.8,
      sd: 2.63,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    medium: {
      v: 17.18,
      sd: 1.6,
      method: "blend",
      basis: ["Mystery Game Puzzles", "WeirdML", "low\u2192medium ratio over 16 AA ladders"],
    },
    xhigh: {
      v: 24.88,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 25.84,
      sd: 0.87,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-oss-20b": {
    minimal: {
      v: 8.08,
      sd: 1.66,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    medium: {
      v: 15.23,
      sd: 1.55,
      method: "blend",
      basis: [
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
        "low\u2192medium ratio over 16 AA ladders",
        "clamped to measured neighbours",
      ],
    },
    xhigh: {
      v: 15.7,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 16.31,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "grok-3-mini": {
    low: { v: 22.85, sd: 7.8, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    high: { v: 24.52, sd: 8.72, method: "benchmark-fit", basis: ["LMArena text Elo", "WeirdML"] },
  },
  "grok-3-mini-beta": {
    low: {
      v: 20.2,
      sd: 10.19,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "Aider polyglot",
        "FrontierMath-2025-02-28-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
      ],
    },
    high: {
      v: 26.33,
      sd: 11.5,
      method: "benchmark-fit",
      basis: [
        "Aider polyglot",
        "FrontierMath-2025-02-28-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
      ],
    },
  },
  "grok-3-mini-reasoning": {
    minimal: {
      v: 12.14,
      sd: 2.49,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 19.13,
      sd: 2.38,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 16 AA ladders"],
    },
    medium: {
      v: 21.89,
      sd: 1.83,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 16 AA ladders"],
    },
    xhigh: {
      v: 23.59,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 24.5,
      sd: 0.83,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "grok-4-0709": {
    high: { v: 30.45, sd: 4.47, method: "benchmark-fit", basis: ["Aider polyglot"] },
  },
  "grok-4-3": {
    minimal: {
      v: 19.62,
      sd: 5.16,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    xhigh: {
      v: 39.13,
      sd: 0.91,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 40.64,
      sd: 1.37,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "grok-4-5": {
    minimal: {
      v: 29.58,
      sd: 6.08,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 46.06,
      sd: 4.39,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "high\u2192low ratio over 16 AA ladders"],
    },
    medium: {
      v: 52.47,
      sd: 3.55,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "high\u2192medium ratio over 16 AA ladders"],
    },
    xhigh: {
      v: 57.49,
      sd: 1.34,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 59.71,
      sd: 2.01,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "grok-4-6": {
    minimal: {
      v: 31.37,
      sd: 8.25,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    max: {
      v: 61.94,
      sd: 1.29,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 6 AA ladders"],
    },
  },
  inkling: {
    low: {
      v: 34.24,
      sd: 2.66,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 9 AA ladders"],
    },
    medium: {
      v: 37.09,
      sd: 3.18,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 11 AA ladders"],
    },
    high: {
      v: 40.84,
      sd: 0.96,
      method: "blend",
      basis: ["WeirdML", "xhigh\u2192high ratio over 7 AA ladders"],
    },
    max: {
      v: 43.65,
      sd: 0.91,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 6 AA ladders"],
    },
  },
  "inkling-small": {
    minimal: { v: 31.96, sd: 5.7, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    low: { v: 33.16, sd: 6.01, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    medium: { v: 38.57, sd: 7.09, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    high: {
      v: 43.68,
      sd: 6.52,
      method: "benchmark-fit",
      basis: ["ARC-AGI", "ARC-AGI-2", "pooled for ladder order"],
    },
    xhigh: {
      v: 43.68,
      sd: 10.45,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "pooled for ladder order",
      ],
    },
  },
  "k2-v2": {
    minimal: {
      v: 6.59,
      sd: 1.74,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    xhigh: {
      v: 14.68,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 15.25,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "kimi-k3": {
    medium: {
      v: 54.24,
      sd: 5.25,
      method: "ladder-shape",
      basis: ["low\u2192medium ratio over 16 AA ladders", "pooled for ladder order"],
    },
    high: {
      v: 54.24,
      sd: 5.57,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "low\u2192high ratio over 16 AA ladders",
        "pooled for ladder order",
      ],
    },
    xhigh: {
      v: 57.86,
      sd: 1.19,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 6 AA ladders"],
    },
  },
  mistral: {
    medium: { v: -22.04, sd: 5.74, method: "benchmark-fit", basis: ["LMArena text Elo"] },
  },
  "muse-glimmer": {
    minimal: {
      v: 18.6,
      sd: 3.82,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 29.32,
      sd: 3.65,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 16 AA ladders"],
    },
    medium: {
      v: 33.55,
      sd: 2.81,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 16 AA ladders"],
    },
    xhigh: {
      v: 36.15,
      sd: 0.84,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 37.55,
      sd: 1.27,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "muse-spark-1-1": {
    low: {
      v: 43.07,
      sd: 3.35,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 9 AA ladders"],
    },
    medium: {
      v: 46.65,
      sd: 4.0,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 11 AA ladders"],
    },
    high: {
      v: 51.7,
      sd: 1.19,
      method: "blend",
      basis: ["DTBench", "LMCA", "xhigh\u2192high ratio over 7 AA ladders"],
    },
    max: {
      v: 54.91,
      sd: 1.15,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 6 AA ladders"],
    },
  },
  "muse-spark-1-2": {
    low: {
      v: 45.96,
      sd: 3.57,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 9 AA ladders"],
    },
    medium: {
      v: 49.78,
      sd: 4.27,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 11 AA ladders"],
    },
    high: {
      v: 55.08,
      sd: 1.3,
      method: "ladder-shape",
      basis: ["xhigh\u2192high ratio over 7 AA ladders"],
    },
    max: {
      v: 58.59,
      sd: 1.22,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 6 AA ladders"],
    },
  },
  "muse-spark-1-3": {
    low: {
      v: 49.21,
      sd: 3.83,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 9 AA ladders"],
    },
    medium: {
      v: 53.3,
      sd: 4.57,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 11 AA ladders"],
    },
    high: {
      v: 58.98,
      sd: 1.39,
      method: "ladder-shape",
      basis: ["xhigh\u2192high ratio over 7 AA ladders"],
    },
  },
  "nova-2-0-lite-reasoning": {
    minimal: {
      v: 10.23,
      sd: 2.69,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    xhigh: {
      v: 21.45,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 22.28,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "nova-2-0-omni-reasoning": {
    minimal: {
      v: 11.3,
      sd: 2.97,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    high: {
      v: 22.36,
      sd: 1.66,
      method: "ladder-shape",
      basis: ["medium\u2192high ratio over 16 AA ladders"],
    },
    xhigh: {
      v: 24.44,
      sd: 2.21,
      method: "ladder-shape",
      basis: ["medium\u2192xhigh ratio over 11 AA ladders"],
    },
    max: {
      v: 24.72,
      sd: 2.2,
      method: "ladder-shape",
      basis: ["medium\u2192max ratio over 5 AA ladders"],
    },
  },
  "nova-2-0-pro": {
    low: { v: 37.28, sd: 7.24, method: "benchmark-fit", basis: ["CritPt"] },
    medium: { v: 37.28, sd: 7.24, method: "benchmark-fit", basis: ["CritPt"] },
  },
  "nova-2-0-pro-reasoning": {
    minimal: {
      v: 11.76,
      sd: 3.09,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    high: {
      v: 23.26,
      sd: 1.72,
      method: "ladder-shape",
      basis: ["medium\u2192high ratio over 16 AA ladders"],
    },
    xhigh: {
      v: 25.41,
      sd: 2.3,
      method: "ladder-shape",
      basis: ["medium\u2192xhigh ratio over 11 AA ladders"],
    },
    max: {
      v: 25.71,
      sd: 2.28,
      method: "ladder-shape",
      basis: ["medium\u2192max ratio over 5 AA ladders"],
    },
  },
  o1: {
    low: {
      v: 22.37,
      sd: 9.03,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
      ],
    },
    medium: {
      v: 26.99,
      sd: 8.92,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "SimpleBench",
        "VPCT",
      ],
    },
    high: {
      v: 27.54,
      sd: 10.54,
      method: "benchmark-fit",
      basis: [
        "APEX-Agents",
        "Aider polyglot",
        "DTBench",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "LMCA",
        "OTIS Mock AIME 2024-2025",
        "SimpleBench",
        "SimpleQA Verified",
        "WeirdML",
      ],
    },
  },
  "o1-mini": {
    medium: {
      v: 14.4,
      sd: 8.74,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "FrontierMath-2025-02-28-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "SimpleBench",
        "WeirdML",
        "pooled for ladder order",
      ],
    },
    high: {
      v: 14.4,
      sd: 7.97,
      method: "benchmark-fit",
      basis: [
        "FrontierMath-2025-02-28-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "pooled for ladder order",
      ],
    },
  },
  "o1-pro": {
    low: { v: 20.94, sd: 4.64, method: "benchmark-fit", basis: ["ARC-AGI"] },
  },
  o3: {
    low: {
      v: 26.69,
      sd: 9.14,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
      ],
    },
    medium: {
      v: 32.65,
      sd: 8.62,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "Aider polyglot",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SWE-Bench verified",
        "VPCT",
      ],
    },
    high: {
      v: 36.53,
      sd: 9.74,
      method: "benchmark-fit",
      basis: [
        "APEX-Agents",
        "ARC-AGI",
        "ARC-AGI-2",
        "Aider polyglot",
        "CritPt",
        "DTBench",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "GSO-Bench",
        "LMCA",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleBench",
        "SimpleQA Verified",
        "WeirdML",
      ],
    },
  },
  "o3-mini": {
    minimal: {
      v: 8.33,
      sd: 1.71,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 13.36,
      sd: 1.61,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "GSO-Bench",
        "OTIS Mock AIME 2024-2025",
        "high\u2192low ratio over 16 AA ladders",
      ],
    },
    medium: {
      v: 15.2,
      sd: 1.24,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "Aider polyglot",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "high\u2192medium ratio over 16 AA ladders",
      ],
    },
    xhigh: {
      v: 16.19,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 16.81,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "o3-pro": {
    low: { v: 30.5, sd: 5.53, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    medium: { v: 33.82, sd: 6.91, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    high: {
      v: 38.14,
      sd: 7.73,
      method: "benchmark-fit",
      basis: ["ARC-AGI", "ARC-AGI-2", "Aider polyglot", "DTBench", "LMCA", "WeirdML"],
    },
  },
  "o4-mini": {
    minimal: {
      v: 13.82,
      sd: 2.84,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 22.04,
      sd: 2.59,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "high\u2192low ratio over 16 AA ladders",
      ],
    },
    medium: {
      v: 25.32,
      sd: 2.0,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "VPCT",
        "high\u2192medium ratio over 16 AA ladders",
      ],
    },
    xhigh: {
      v: 26.86,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 27.9,
      sd: 0.94,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "openai/gpt-oss-120b": {
    low: {
      v: 35.78,
      sd: 7.24,
      method: "benchmark-fit",
      basis: ["CritPt", "pooled for ladder order"],
    },
    high: {
      v: 35.78,
      sd: 11.84,
      method: "benchmark-fit",
      basis: [
        "Aider polyglot",
        "CritPt",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
        "pooled for ladder order",
      ],
    },
  },
  "qwen2-5": {
    max: { v: 23.48, sd: 5.74, method: "benchmark-fit", basis: ["LMArena text Elo"] },
  },
  "qwen3-8-27b": {
    minimal: {
      v: 23.63,
      sd: 6.22,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    high: {
      v: 46.75,
      sd: 3.46,
      method: "ladder-shape",
      basis: ["medium\u2192high ratio over 16 AA ladders"],
    },
    max: {
      v: 53.7,
      sd: 1.12,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 6 AA ladders"],
    },
  },
  "qwen3-8-max": {
    xhigh: {
      v: 52.48,
      sd: 7.42,
      method: "benchmark-fit",
      basis: [
        "DTBench",
        "DeepSWE",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "LMCA",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
      ],
    },
  },
  "sarvam-105b": {
    minimal: {
      v: 6.31,
      sd: 1.3,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 9.96,
      sd: 1.24,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 16 AA ladders"],
    },
    medium: {
      v: 11.39,
      sd: 0.95,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 16 AA ladders"],
    },
    xhigh: {
      v: 12.27,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 12.75,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "sarvam-30b": {
    minimal: {
      v: 3.39,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 5.34,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 16 AA ladders"],
    },
    medium: {
      v: 6.11,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 16 AA ladders"],
    },
    xhigh: {
      v: 6.59,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 7 AA ladders"],
    },
    max: {
      v: 6.84,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
};
