// tinker-ui/src/panels/aa-effort-estimate.ts
// GENERATED by model-rank-refresh/scripts/estimate_effort_index.py — do not hand-edit.
// Retrieved: 2026-09-07T04:04:25+00:00
//
// ESTIMATED Artificial Analysis Intelligence Index for (family, effort) cells AA did
// not publish. The user 2026-09-02: approximate from other measurements, as long as the
// chart never confuses an estimate with a measurement. Two methods, both named on
// every cell:
//   benchmark-fit — R²-weighted mean of per-benchmark linear fits AA ~ a + b·score,
//                   fitted on cells AA DID score at that effort; basis lists the
//                   benchmarks that ran this model at this effort (Epoch AI hub,
//                   LMArena text Elo).
//   ladder-shape  — the model's nearest AA-measured rung × the mean AA ratio
//                   between those two efforts over AA's own multi-rung families.
//                   Assumes an average ladder shape; sd is the spread of those ratios.
//   blend         — both, inverse-variance weighted.
// Every estimate is clamped between the model's measured neighbours and kept
// non-decreasing across efforts (pool-adjacent-violators), because a ladder
// whose 'high' outscores its measured 'max' is noise, not a finding.
// A cell AA measured is NEVER here — aa-effort-index.ts wins.
//
// Fits kept (n ≥ 6, R² ≥ 0.55):
//   FrontierMath-2025-02-28-Private: n=16 R²=0.90 rmse=3.6
//   GSO-Bench: n=6 R²=0.89 rmse=4.1
//   APEX-Agents: n=13 R²=0.88 rmse=3.2
//   ARC-AGI: n=72 R²=0.88 rmse=4.6
//   DeepSWE: n=51 R²=0.86 rmse=2.3
//   LMArena text Elo: n=15 R²=0.86 rmse=5.6
//   FrontierMath-Tier-4-2025-07-01-Private: n=16 R²=0.85 rmse=4.4
//   OSWorld 2.0: n=10 R²=0.84 rmse=1.9
//   FrontierMath-Tiers-1-3-v2-Private: n=39 R²=0.84 rmse=5.7
//   LMCA: n=36 R²=0.84 rmse=5.0
//   ARC-AGI-2: n=71 R²=0.83 rmse=5.4
//   VPCT: n=8 R²=0.82 rmse=3.0
//   DTBench: n=36 R²=0.81 rmse=5.4
//   SWE-Bench verified: n=9 R²=0.81 rmse=3.6
//   GPQA diamond: n=53 R²=0.70 rmse=7.5
//   WeirdML: n=36 R²=0.69 rmse=7.4
//   SimpleBench: n=9 R²=0.69 rmse=8.1
//   Aider polyglot: n=6 R²=0.67 rmse=3.7
//   OTIS Mock AIME 2024-2025: n=54 R²=0.66 rmse=8.1
//   CritPt: n=72 R²=0.65 rmse=6.1
//   Mystery Game Puzzles: n=47 R²=0.63 rmse=8.6
//   ProofBench: n=25 R²=0.62 rmse=6.3
//   EBR-bench: n=15 R²=0.61 rmse=5.1
//   FrontierMath-Tier-4-v2-Private: n=38 R²=0.59 rmse=7.5
//   SimpleQA Verified: n=34 R²=0.58 rmse=7.5
//   PostTrainBench: n=6 R²=0.57 rmse=2.5

import type { AaEffort } from "./aa-effort-index.js";

export interface AaEstimate {
  /** Estimated AA Intelligence Index. */
  v: number;
  /** Spread of the estimate, AA points. */
  sd: number;
  method: "benchmark-fit" | "ladder-shape" | "blend";
  /** Benchmarks (or the AA-ladder delta) the number rests on. */
  basis: string[];
}

export const AA_EFFORT_ESTIMATE: Record<string, Partial<Record<AaEffort, AaEstimate>>> = {
  "claude-fable-5": {
    low: {
      v: 41.68,
      sd: 4.66,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DeepSWE",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "max\u2192low ratio over 7 AA ladders",
      ],
    },
    medium: {
      v: 47.13,
      sd: 3.31,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "DeepSWE", "max\u2192medium ratio over 6 AA ladders"],
    },
    high: {
      v: 49.71,
      sd: 2.32,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DeepSWE",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
        "max\u2192high ratio over 7 AA ladders",
      ],
    },
    xhigh: {
      v: 51.83,
      sd: 0.83,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DeepSWE",
        "SimpleQA Verified",
        "max\u2192xhigh ratio over 7 AA ladders",
      ],
    },
  },
  "claude-fable-5-1": {
    minimal: {
      v: 22.2,
      sd: 10.59,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "claude-opus-4-5": {
    high: { v: 38.05, sd: 5.2, method: "benchmark-fit", basis: ["DTBench", "LMCA"] },
  },
  "claude-opus-4-6-adaptive": {
    low: {
      v: 27.46,
      sd: 3.43,
      method: "blend",
      basis: ["Mystery Game Puzzles", "max\u2192low ratio over 7 AA ladders"],
    },
    medium: {
      v: 31.49,
      sd: 3.32,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 6 AA ladders"],
    },
    high: {
      v: 35.03,
      sd: 1.59,
      method: "blend",
      basis: ["GSO-Bench", "WeirdML", "max\u2192high ratio over 7 AA ladders"],
    },
    xhigh: {
      v: 35.49,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 7 AA ladders"],
    },
  },
  "claude-opus-4-7": {
    low: {
      v: 38.71,
      sd: 3.43,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "max\u2192low ratio over 7 AA ladders"],
    },
    medium: {
      v: 41.06,
      sd: 3.14,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "max\u2192medium ratio over 6 AA ladders"],
    },
    high: {
      v: 42.11,
      sd: 1.91,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GSO-Bench",
        "WeirdML",
        "max\u2192high ratio over 7 AA ladders",
      ],
    },
    xhigh: {
      v: 43.15,
      sd: 0.79,
      method: "blend",
      basis: [
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "PostTrainBench",
        "SimpleQA Verified",
        "max\u2192xhigh ratio over 7 AA ladders",
      ],
    },
  },
  "claude-opus-4-8": {
    low: {
      v: 38.85,
      sd: 3.86,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DeepSWE",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "max\u2192low ratio over 7 AA ladders",
      ],
    },
    medium: {
      v: 42.53,
      sd: 3.4,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DeepSWE",
        "WeirdML",
        "max\u2192medium ratio over 6 AA ladders",
      ],
    },
    high: {
      v: 45.05,
      sd: 1.94,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DeepSWE",
        "PostTrainBench",
        "max\u2192high ratio over 7 AA ladders",
      ],
    },
    xhigh: {
      v: 46.54,
      sd: 0.8,
      method: "blend",
      basis: [
        "DeepSWE",
        "Mystery Game Puzzles",
        "WeirdML",
        "max\u2192xhigh ratio over 7 AA ladders",
      ],
    },
  },
  "claude-opus-5": {
    minimal: {
      v: 20.83,
      sd: 9.94,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "claude-sonnet-4-6-adaptive": {
    low: {
      v: 29.66,
      sd: 3.59,
      method: "blend",
      basis: ["Mystery Game Puzzles", "max\u2192low ratio over 7 AA ladders"],
    },
    medium: {
      v: 33.79,
      sd: 3.17,
      method: "blend",
      basis: [
        "GPQA diamond",
        "OSWorld 2.0",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
        "max\u2192medium ratio over 6 AA ladders",
      ],
    },
    high: {
      v: 36.11,
      sd: 1.7,
      method: "blend",
      basis: [
        "APEX-Agents",
        "ARC-AGI",
        "ARC-AGI-2",
        "DeepSWE",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "max\u2192high ratio over 7 AA ladders",
      ],
    },
    xhigh: {
      v: 37.5,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 7 AA ladders"],
    },
  },
  "claude-sonnet-5": {
    low: {
      v: 35.44,
      sd: 2.06,
      method: "blend",
      basis: ["DeepSWE", "max\u2192low ratio over 7 AA ladders"],
    },
    medium: {
      v: 38.86,
      sd: 2.01,
      method: "blend",
      basis: ["DeepSWE", "max\u2192medium ratio over 6 AA ladders"],
    },
    high: {
      v: 42.01,
      sd: 1.97,
      method: "blend",
      basis: ["CritPt", "DeepSWE", "WeirdML", "max\u2192high ratio over 7 AA ladders"],
    },
    xhigh: {
      v: 43.93,
      sd: 0.8,
      method: "blend",
      basis: [
        "DeepSWE",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "max\u2192xhigh ratio over 7 AA ladders",
      ],
    },
  },
  "deepseek-v4-flash": {
    low: {
      v: 34.6,
      sd: 3.37,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "max\u2192low ratio over 7 AA ladders"],
    },
    medium: {
      v: 35.32,
      sd: 3.72,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 6 AA ladders"],
    },
    high: {
      v: 38.26,
      sd: 1.82,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "CritPt", "WeirdML", "max\u2192high ratio over 7 AA ladders"],
    },
    xhigh: {
      v: 39.81,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 7 AA ladders"],
    },
  },
  "deepseek-v4-flash-0420": {
    minimal: {
      v: 13.27,
      sd: 5.72,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 24.62,
      sd: 4.47,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 17 AA ladders"],
    },
    medium: {
      v: 29.14,
      sd: 3.19,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 17 AA ladders"],
    },
    xhigh: {
      v: 30.73,
      sd: 1.08,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders", "clamped to measured neighbours"],
    },
  },
  "deepseek-v4-flash-vision": {
    low: {
      v: 31.57,
      sd: 4.18,
      method: "ladder-shape",
      basis: ["max\u2192low ratio over 7 AA ladders"],
    },
    medium: {
      v: 35.19,
      sd: 3.71,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 6 AA ladders"],
    },
    high: {
      v: 38.21,
      sd: 1.84,
      method: "ladder-shape",
      basis: ["max\u2192high ratio over 7 AA ladders"],
    },
    xhigh: {
      v: 39.66,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 7 AA ladders"],
    },
  },
  "deepseek-v4-pro": {
    low: {
      v: 36.56,
      sd: 3.41,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "max\u2192low ratio over 7 AA ladders",
        "pooled for ladder order",
      ],
    },
    medium: {
      v: 36.56,
      sd: 3.84,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 6 AA ladders", "pooled for ladder order"],
    },
    high: {
      v: 39.51,
      sd: 1.87,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "CritPt",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
        "max\u2192high ratio over 7 AA ladders",
      ],
    },
    xhigh: {
      v: 41.06,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 7 AA ladders"],
    },
  },
  "deepseek-v4-pro-0424": {
    minimal: {
      v: 15.12,
      sd: 6.52,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 28.04,
      sd: 5.09,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 17 AA ladders"],
    },
    medium: {
      v: 33.19,
      sd: 3.63,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 17 AA ladders"],
    },
    xhigh: {
      v: 36.02,
      sd: 1.23,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 36.98,
      sd: 1.85,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gemini-3-1-flash-lite": {
    minimal: {
      v: 14.03,
      sd: 11.76,
      method: "benchmark-fit",
      basis: ["FrontierMath-Tiers-1-3-v2-Private", "GPQA diamond", "OTIS Mock AIME 2024-2025"],
    },
    low: {
      v: 15.86,
      sd: 10.33,
      method: "benchmark-fit",
      basis: ["FrontierMath-Tiers-1-3-v2-Private", "GPQA diamond", "OTIS Mock AIME 2024-2025"],
    },
    high: {
      v: 26.49,
      sd: 7.88,
      method: "benchmark-fit",
      basis: [
        "DTBench",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "LMCA",
        "OTIS Mock AIME 2024-2025",
      ],
    },
  },
  "gemini-3-1-pro": {
    low: { v: 36.69, sd: 8.56, method: "benchmark-fit", basis: ["Mystery Game Puzzles"] },
    medium: { v: 38.51, sd: 8.56, method: "benchmark-fit", basis: ["Mystery Game Puzzles"] },
    high: {
      v: 45.33,
      sd: 8.25,
      method: "benchmark-fit",
      basis: [
        "DTBench",
        "GPQA diamond",
        "LMCA",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
      ],
    },
  },
  "gemini-3-5-flash": {
    low: {
      v: 34.0,
      sd: 4.02,
      method: "blend",
      basis: [
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "medium\u2192low ratio over 17 AA ladders",
      ],
    },
    xhigh: {
      v: 41.3,
      sd: 1.42,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 42.41,
      sd: 2.12,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gemini-3-5-flash-lite": {
    minimal: {
      v: 13.01,
      sd: 4.65,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "high\u2192minimal ratio over 4 AA ladders",
      ],
    },
    low: {
      v: 22.02,
      sd: 3.74,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "high\u2192low ratio over 17 AA ladders",
      ],
    },
    medium: {
      v: 25.11,
      sd: 2.56,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "high\u2192medium ratio over 17 AA ladders"],
    },
    xhigh: {
      v: 28.67,
      sd: 0.98,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 29.43,
      sd: 1.47,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gemini-3-6-flash": {
    minimal: {
      v: 21.38,
      sd: 5.96,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "high\u2192minimal ratio over 4 AA ladders",
      ],
    },
    low: {
      v: 33.39,
      sd: 4.62,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "high\u2192low ratio over 17 AA ladders",
      ],
    },
    medium: {
      v: 39.33,
      sd: 3.29,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "high\u2192medium ratio over 17 AA ladders"],
    },
    xhigh: {
      v: 41.88,
      sd: 1.44,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 43.0,
      sd: 2.15,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gemini-3-7-flash": {
    minimal: {
      v: 18.25,
      sd: 8.7,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    xhigh: {
      v: 47.04,
      sd: 1.61,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 48.29,
      sd: 2.41,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gemini-3-8-flash": {
    minimal: {
      v: 19.67,
      sd: 9.38,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    xhigh: {
      v: 48.94,
      sd: 1.68,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 50.24,
      sd: 2.51,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gemini-3-flash": {
    minimal: { v: 34.27, sd: 8.56, method: "benchmark-fit", basis: ["Mystery Game Puzzles"] },
    low: { v: 34.87, sd: 8.56, method: "benchmark-fit", basis: ["Mystery Game Puzzles"] },
    high: {
      v: 39.24,
      sd: 9.01,
      method: "benchmark-fit",
      basis: [
        "DTBench",
        "GPQA diamond",
        "LMCA",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
      ],
    },
  },
  "gemini-3-flash-thinking": {
    minimal: { v: 40.12, sd: 5.56, method: "benchmark-fit", basis: ["LMArena text Elo"] },
  },
  "gemini-3-pro": {
    minimal: {
      v: 14.16,
      sd: 6.1,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    medium: {
      v: 31.36,
      sd: 7.34,
      method: "ladder-shape",
      basis: ["low\u2192medium ratio over 17 AA ladders"],
    },
    xhigh: {
      v: 33.73,
      sd: 1.16,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 34.63,
      sd: 1.73,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gemma-4-26b-a4b-it": {
    minimal: {
      v: 27.42,
      sd: 9.16,
      method: "benchmark-fit",
      basis: ["GPQA diamond", "OTIS Mock AIME 2024-2025"],
    },
  },
  "gemma-4-31b-it": {
    minimal: {
      v: 25.64,
      sd: 7.82,
      method: "benchmark-fit",
      basis: ["GPQA diamond", "OTIS Mock AIME 2024-2025"],
    },
  },
  "glm-5-2": {
    minimal: { v: 30.02, sd: 8.56, method: "benchmark-fit", basis: ["Mystery Game Puzzles"] },
    low: {
      v: 32.73,
      sd: 3.85,
      method: "blend",
      basis: [
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "max\u2192low ratio over 7 AA ladders",
      ],
    },
    medium: {
      v: 35.03,
      sd: 3.5,
      method: "blend",
      basis: ["Mystery Game Puzzles", "max\u2192medium ratio over 6 AA ladders"],
    },
    high: {
      v: 39.3,
      sd: 1.79,
      method: "blend",
      basis: ["DeepSWE", "WeirdML", "max\u2192high ratio over 7 AA ladders"],
    },
    xhigh: {
      v: 41.02,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 7 AA ladders"],
    },
  },
  "glm-5-3": {
    low: {
      v: 37.69,
      sd: 5.0,
      method: "ladder-shape",
      basis: ["max\u2192low ratio over 7 AA ladders"],
    },
    medium: {
      v: 42.02,
      sd: 4.43,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 6 AA ladders"],
    },
    high: {
      v: 45.63,
      sd: 2.2,
      method: "ladder-shape",
      basis: ["max\u2192high ratio over 7 AA ladders"],
    },
    xhigh: {
      v: 47.36,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 7 AA ladders"],
    },
  },
  "glm-5-3-flash": {
    low: {
      v: 35.86,
      sd: 4.75,
      method: "ladder-shape",
      basis: ["max\u2192low ratio over 7 AA ladders"],
    },
    medium: {
      v: 39.98,
      sd: 4.21,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 6 AA ladders"],
    },
    high: {
      v: 43.41,
      sd: 2.09,
      method: "ladder-shape",
      basis: ["max\u2192high ratio over 7 AA ladders"],
    },
    xhigh: {
      v: 45.06,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 7 AA ladders"],
    },
  },
  "gpt-5": {
    xhigh: {
      v: 28.16,
      sd: 0.97,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 28.91,
      sd: 1.45,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-1": {
    minimal: {
      v: 12.68,
      sd: 5.46,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 22.89,
      sd: 3.71,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "high\u2192low ratio over 17 AA ladders",
      ],
    },
    medium: {
      v: 27.73,
      sd: 2.84,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "VPCT",
        "high\u2192medium ratio over 17 AA ladders",
      ],
    },
    xhigh: {
      v: 30.2,
      sd: 1.04,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 31.01,
      sd: 1.55,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-1-codex": {
    minimal: {
      v: 12.15,
      sd: 5.24,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 22.54,
      sd: 4.09,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 17 AA ladders"],
    },
    medium: {
      v: 26.69,
      sd: 2.92,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 17 AA ladders"],
    },
    xhigh: {
      v: 28.96,
      sd: 0.99,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 29.73,
      sd: 1.49,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-1-codex-mini": {
    minimal: {
      v: 10.45,
      sd: 4.51,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 19.38,
      sd: 3.52,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 17 AA ladders"],
    },
    medium: {
      v: 22.95,
      sd: 2.51,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 17 AA ladders"],
    },
    xhigh: {
      v: 24.9,
      sd: 0.85,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 25.57,
      sd: 1.28,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-2": {
    minimal: {
      v: 13.01,
      sd: 6.2,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 26.82,
      sd: 3.35,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "WeirdML",
        "medium\u2192low ratio over 17 AA ladders",
      ],
    },
    high: {
      v: 33.06,
      sd: 2.83,
      method: "blend",
      basis: [
        "APEX-Agents",
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "GPQA diamond",
        "GSO-Bench",
        "LMArena text Elo",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SWE-Bench verified",
        "SimpleBench",
        "SimpleQA Verified",
        "VPCT",
        "medium\u2192high ratio over 17 AA ladders",
      ],
    },
    max: {
      v: 35.86,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-2-codex": {
    low: {
      v: 26.31,
      sd: 2.68,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 10 AA ladders"],
    },
    medium: {
      v: 28.65,
      sd: 2.81,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 12 AA ladders"],
    },
    high: {
      v: 31.78,
      sd: 1.06,
      method: "ladder-shape",
      basis: ["xhigh\u2192high ratio over 8 AA ladders"],
    },
    max: {
      v: 33.86,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-2-pro": {
    medium: { v: 37.92, sd: 6.0, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    high: { v: 41.71, sd: 5.24, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    xhigh: {
      v: 44.81,
      sd: 6.01,
      method: "benchmark-fit",
      basis: ["ARC-AGI", "FrontierMath-Tier-4-v2-Private", "FrontierMath-Tiers-1-3-v2-Private"],
    },
  },
  "gpt-5-3-codex": {
    low: {
      v: 29.45,
      sd: 2.99,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 10 AA ladders"],
    },
    medium: {
      v: 32.07,
      sd: 3.15,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 12 AA ladders"],
    },
    high: {
      v: 35.55,
      sd: 1.13,
      method: "blend",
      basis: ["SWE-Bench verified", "xhigh\u2192high ratio over 8 AA ladders"],
    },
    max: {
      v: 37.9,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-4": {
    medium: {
      v: 39.56,
      sd: 5.64,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "low\u2192medium ratio over 17 AA ladders",
      ],
    },
    high: {
      v: 41.25,
      sd: 1.35,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "GSO-Bench",
        "OTIS Mock AIME 2024-2025",
        "PostTrainBench",
        "SWE-Bench verified",
        "xhigh\u2192high ratio over 8 AA ladders",
      ],
    },
    max: {
      v: 43.94,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-4-mini": {
    minimal: {
      v: 9.75,
      sd: 4.65,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 19.82,
      sd: 2.67,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tiers-1-3-v2-Private",
        "Mystery Game Puzzles",
        "medium\u2192low ratio over 17 AA ladders",
      ],
    },
    high: {
      v: 24.79,
      sd: 2.26,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "GPQA diamond",
        "LMArena text Elo",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "WeirdML",
        "medium\u2192high ratio over 17 AA ladders",
      ],
    },
    max: {
      v: 32.75,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-4-nano": {
    minimal: {
      v: 9.89,
      sd: 4.72,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 20.16,
      sd: 2.68,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "medium\u2192low ratio over 17 AA ladders",
      ],
    },
    high: {
      v: 24.87,
      sd: 2.27,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "FrontierMath-Tier-4-v2-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "LMArena text Elo",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "ProofBench",
        "SimpleQA Verified",
        "WeirdML",
        "medium\u2192high ratio over 17 AA ladders",
      ],
    },
    max: {
      v: 31.73,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-4-pro": {
    xhigh: {
      v: 47.2,
      sd: 7.01,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "CritPt",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-v2-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "SimpleQA Verified",
      ],
    },
  },
  "gpt-5-5": {
    minimal: {
      v: 17.34,
      sd: 8.27,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    max: {
      v: 46.8,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-5-pro": {
    high: {
      v: 49.87,
      sd: 6.28,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "SimpleBench",
        "pooled for ladder order",
      ],
    },
    xhigh: {
      v: 49.87,
      sd: 6.86,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "CritPt",
        "DTBench",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "FrontierMath-Tier-4-v2-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "LMCA",
        "OTIS Mock AIME 2024-2025",
        "pooled for ladder order",
      ],
    },
  },
  "gpt-5-6-luna": {
    minimal: {
      v: 12.7,
      sd: 6.06,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "gpt-5-6-sol": {
    minimal: {
      v: 19.34,
      sd: 9.22,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "gpt-5-6-terra": {
    minimal: {
      v: 15.66,
      sd: 7.47,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "gpt-5-codex": {
    minimal: {
      v: 12.73,
      sd: 5.49,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 23.61,
      sd: 4.28,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 17 AA ladders"],
    },
    medium: {
      v: 27.95,
      sd: 3.06,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 17 AA ladders"],
    },
    xhigh: {
      v: 30.33,
      sd: 1.04,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 31.14,
      sd: 1.56,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-mini": {
    low: {
      v: 18.42,
      sd: 2.64,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tiers-1-3-v2-Private",
        "medium\u2192low ratio over 17 AA ladders",
        "clamped to measured neighbours",
      ],
    },
    xhigh: {
      v: 24.22,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders", "clamped to measured neighbours"],
    },
    max: {
      v: 24.22,
      sd: 0.98,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders", "clamped to measured neighbours"],
    },
  },
  "gpt-5-nano": {
    low: {
      v: 11.16,
      sd: 1.55,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
        "medium\u2192low ratio over 17 AA ladders",
      ],
    },
    xhigh: {
      v: 14.24,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 14.62,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-5-pro": {
    high: {
      v: 35.21,
      sd: 7.43,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "FrontierMath-Tier-4-v2-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "SimpleBench",
        "WeirdML",
      ],
    },
  },
  "gpt-6-astra": {
    minimal: {
      v: 21.98,
      sd: 10.48,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "gpt-oss-120b": {
    minimal: {
      v: 6.79,
      sd: 2.93,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    medium: {
      v: 11.55,
      sd: 2.38,
      method: "blend",
      basis: ["Mystery Game Puzzles", "WeirdML", "low\u2192medium ratio over 17 AA ladders"],
    },
    xhigh: {
      v: 16.19,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 16.62,
      sd: 0.83,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "gpt-oss-20b": {
    minimal: {
      v: 3.99,
      sd: 1.72,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    medium: {
      v: 9.14,
      sd: 2.28,
      method: "blend",
      basis: [
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
        "low\u2192medium ratio over 17 AA ladders",
        "clamped to measured neighbours",
      ],
    },
    xhigh: {
      v: 9.5,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 9.75,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "grok-3-mini": {
    low: { v: 15.68, sd: 7.21, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    high: { v: 17.34, sd: 7.61, method: "benchmark-fit", basis: ["LMArena text Elo", "WeirdML"] },
  },
  "grok-3-mini-beta": {
    low: {
      v: 13.14,
      sd: 9.19,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "Aider polyglot",
        "FrontierMath-2025-02-28-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
      ],
    },
    high: {
      v: 18.8,
      sd: 10.11,
      method: "benchmark-fit",
      basis: [
        "Aider polyglot",
        "FrontierMath-2025-02-28-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
      ],
    },
  },
  "grok-3-mini-reasoning": {
    minimal: {
      v: 7.07,
      sd: 3.05,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 13.11,
      sd: 2.38,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 17 AA ladders"],
    },
    medium: {
      v: 15.53,
      sd: 1.7,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 17 AA ladders"],
    },
    xhigh: {
      v: 16.85,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 17.3,
      sd: 0.87,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "grok-4-0709": {
    high: { v: 22.98, sd: 3.69, method: "benchmark-fit", basis: ["Aider polyglot"] },
  },
  "grok-4-3": {
    minimal: {
      v: 12.23,
      sd: 5.83,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    xhigh: {
      v: 31.12,
      sd: 1.07,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 31.95,
      sd: 1.6,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "grok-4-5": {
    minimal: {
      v: 19.84,
      sd: 8.55,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 36.64,
      sd: 4.58,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "high\u2192low ratio over 17 AA ladders"],
    },
    medium: {
      v: 42.81,
      sd: 3.59,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "high\u2192medium ratio over 17 AA ladders"],
    },
    xhigh: {
      v: 47.28,
      sd: 1.62,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 48.54,
      sd: 2.43,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "grok-4-6": {
    minimal: {
      v: 20.55,
      sd: 9.8,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    max: {
      v: 51.22,
      sd: 0.84,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 7 AA ladders"],
    },
  },
  inkling: {
    low: {
      v: 25.65,
      sd: 2.61,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 10 AA ladders"],
    },
    medium: {
      v: 27.92,
      sd: 2.74,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 12 AA ladders"],
    },
    high: {
      v: 30.68,
      sd: 1.03,
      method: "blend",
      basis: ["WeirdML", "xhigh\u2192high ratio over 8 AA ladders"],
    },
    max: {
      v: 33.0,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 7 AA ladders"],
    },
  },
  "inkling-small": {
    minimal: { v: 24.06, sd: 5.27, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    low: { v: 25.17, sd: 5.58, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    medium: { v: 30.2, sd: 6.64, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    high: {
      v: 35.03,
      sd: 6.12,
      method: "benchmark-fit",
      basis: ["ARC-AGI", "ARC-AGI-2", "pooled for ladder order"],
    },
    xhigh: {
      v: 35.03,
      sd: 9.27,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tier-4-v2-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "pooled for ladder order",
      ],
    },
  },
  "k2-v2": {
    minimal: {
      v: 2.78,
      sd: 1.33,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    xhigh: {
      v: 8.62,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 8.85,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "kimi-k3": {
    medium: {
      v: 43.52,
      sd: 10.37,
      method: "ladder-shape",
      basis: ["low\u2192medium ratio over 17 AA ladders", "pooled for ladder order"],
    },
    high: {
      v: 43.52,
      sd: 6.03,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "low\u2192high ratio over 17 AA ladders",
        "pooled for ladder order",
      ],
    },
    xhigh: {
      v: 48.97,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 7 AA ladders"],
    },
  },
  mistral: {
    medium: { v: -25.71, sd: 5.56, method: "benchmark-fit", basis: ["LMArena text Elo"] },
  },
  "muse-glimmer": {
    minimal: {
      v: 10.64,
      sd: 4.59,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 19.73,
      sd: 3.58,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 17 AA ladders"],
    },
    medium: {
      v: 23.36,
      sd: 2.55,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 17 AA ladders"],
    },
    xhigh: {
      v: 25.34,
      sd: 0.87,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 26.02,
      sd: 1.3,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "muse-spark-1-1": {
    low: {
      v: 32.82,
      sd: 3.34,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 10 AA ladders"],
    },
    medium: {
      v: 35.73,
      sd: 3.51,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 12 AA ladders"],
    },
    high: {
      v: 39.86,
      sd: 1.29,
      method: "blend",
      basis: ["DTBench", "LMCA", "xhigh\u2192high ratio over 8 AA ladders"],
    },
    max: {
      v: 42.23,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 7 AA ladders"],
    },
  },
  "muse-spark-1-2": {
    low: {
      v: 37.34,
      sd: 3.8,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 10 AA ladders"],
    },
    medium: {
      v: 40.66,
      sd: 3.99,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 12 AA ladders"],
    },
    high: {
      v: 45.1,
      sd: 1.51,
      method: "ladder-shape",
      basis: ["xhigh\u2192high ratio over 8 AA ladders"],
    },
    max: {
      v: 48.06,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 7 AA ladders"],
    },
  },
  "muse-spark-1-3": {
    low: {
      v: 41.1,
      sd: 4.18,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 10 AA ladders"],
    },
    medium: {
      v: 44.75,
      sd: 4.39,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 12 AA ladders"],
    },
    high: {
      v: 49.64,
      sd: 1.66,
      method: "ladder-shape",
      basis: ["xhigh\u2192high ratio over 8 AA ladders"],
    },
  },
  "nova-2-0-lite-reasoning": {
    minimal: {
      v: 5.42,
      sd: 2.58,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    xhigh: {
      v: 14.87,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 15.27,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "nova-2-0-omni-reasoning": {
    minimal: {
      v: 6.2,
      sd: 2.95,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    high: {
      v: 15.53,
      sd: 1.49,
      method: "ladder-shape",
      basis: ["medium\u2192high ratio over 17 AA ladders"],
    },
    xhigh: {
      v: 17.14,
      sd: 1.8,
      method: "ladder-shape",
      basis: ["medium\u2192xhigh ratio over 12 AA ladders"],
    },
    max: {
      v: 17.24,
      sd: 2.02,
      method: "ladder-shape",
      basis: ["medium\u2192max ratio over 6 AA ladders"],
    },
  },
  "nova-2-0-pro": {
    low: { v: 27.94, sd: 6.11, method: "benchmark-fit", basis: ["CritPt"] },
    medium: { v: 27.94, sd: 6.11, method: "benchmark-fit", basis: ["CritPt"] },
  },
  "nova-2-0-pro-reasoning": {
    minimal: {
      v: 6.52,
      sd: 3.11,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    high: {
      v: 16.35,
      sd: 1.57,
      method: "ladder-shape",
      basis: ["medium\u2192high ratio over 17 AA ladders"],
    },
    xhigh: {
      v: 18.05,
      sd: 1.89,
      method: "ladder-shape",
      basis: ["medium\u2192xhigh ratio over 12 AA ladders"],
    },
    max: {
      v: 18.15,
      sd: 2.13,
      method: "ladder-shape",
      basis: ["medium\u2192max ratio over 6 AA ladders"],
    },
  },
  o1: {
    low: {
      v: 15.1,
      sd: 8.3,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
      ],
    },
    medium: {
      v: 19.54,
      sd: 8.27,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "SimpleBench",
        "VPCT",
      ],
    },
    high: {
      v: 19.87,
      sd: 9.6,
      method: "benchmark-fit",
      basis: [
        "APEX-Agents",
        "Aider polyglot",
        "DTBench",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "LMCA",
        "OTIS Mock AIME 2024-2025",
        "SimpleBench",
        "SimpleQA Verified",
        "WeirdML",
      ],
    },
  },
  "o1-mini": {
    medium: {
      v: 8.19,
      sd: 7.82,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "FrontierMath-2025-02-28-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "SimpleBench",
        "WeirdML",
        "pooled for ladder order",
      ],
    },
    high: {
      v: 8.19,
      sd: 7.14,
      method: "benchmark-fit",
      basis: [
        "FrontierMath-2025-02-28-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "pooled for ladder order",
      ],
    },
  },
  "o1-pro": {
    low: { v: 13.82, sd: 4.58, method: "benchmark-fit", basis: ["ARC-AGI"] },
  },
  o3: {
    low: {
      v: 19.25,
      sd: 8.2,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
      ],
    },
    medium: {
      v: 24.78,
      sd: 7.69,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "Aider polyglot",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SWE-Bench verified",
        "VPCT",
      ],
    },
    high: {
      v: 28.14,
      sd: 8.73,
      method: "benchmark-fit",
      basis: [
        "APEX-Agents",
        "ARC-AGI",
        "ARC-AGI-2",
        "Aider polyglot",
        "CritPt",
        "DTBench",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "GSO-Bench",
        "LMCA",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleBench",
        "SimpleQA Verified",
        "WeirdML",
      ],
    },
  },
  "o3-mini": {
    minimal: {
      v: 4.2,
      sd: 1.81,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 7.95,
      sd: 1.39,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "GSO-Bench",
        "OTIS Mock AIME 2024-2025",
        "high\u2192low ratio over 17 AA ladders",
      ],
    },
    medium: {
      v: 9.35,
      sd: 1.0,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "Aider polyglot",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "high\u2192medium ratio over 17 AA ladders",
      ],
    },
    xhigh: {
      v: 10.01,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 10.28,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "o3-pro": {
    low: { v: 22.71, sd: 5.1, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    medium: { v: 25.76, sd: 6.45, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    high: {
      v: 29.58,
      sd: 6.87,
      method: "benchmark-fit",
      basis: ["ARC-AGI", "ARC-AGI-2", "Aider polyglot", "DTBench", "LMCA", "WeirdML"],
    },
  },
  "o4-mini": {
    minimal: {
      v: 8.34,
      sd: 3.6,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 15.68,
      sd: 2.65,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "high\u2192low ratio over 17 AA ladders",
      ],
    },
    medium: {
      v: 18.67,
      sd: 1.91,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "VPCT",
        "high\u2192medium ratio over 17 AA ladders",
      ],
    },
    xhigh: {
      v: 19.87,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 20.4,
      sd: 1.02,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "openai/gpt-oss-120b": {
    low: {
      v: 26.73,
      sd: 6.11,
      method: "benchmark-fit",
      basis: ["CritPt", "pooled for ladder order"],
    },
    high: {
      v: 26.73,
      sd: 10.81,
      method: "benchmark-fit",
      basis: [
        "Aider polyglot",
        "CritPt",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
        "pooled for ladder order",
      ],
    },
  },
  "qwen2-5": {
    max: { v: 16.54, sd: 5.56, method: "benchmark-fit", basis: ["LMArena text Elo"] },
  },
  "qwen3-8-27b": {
    minimal: {
      v: 14.8,
      sd: 7.06,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    high: {
      v: 37.1,
      sd: 3.56,
      method: "ladder-shape",
      basis: ["medium\u2192high ratio over 17 AA ladders"],
    },
    max: {
      v: 42.48,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 7 AA ladders"],
    },
  },
  "qwen3-8-max": {
    xhigh: {
      v: 42.69,
      sd: 6.86,
      method: "benchmark-fit",
      basis: [
        "DTBench",
        "DeepSWE",
        "FrontierMath-Tier-4-v2-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "LMCA",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
      ],
    },
  },
  "sarvam-105b": {
    minimal: {
      v: 2.69,
      sd: 1.16,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 4.98,
      sd: 0.9,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 17 AA ladders"],
    },
    medium: {
      v: 5.9,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 17 AA ladders"],
    },
    xhigh: {
      v: 6.4,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 6.57,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
  "sarvam-30b": {
    minimal: {
      v: 0.48,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 0.89,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 17 AA ladders"],
    },
    medium: {
      v: 1.05,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 17 AA ladders"],
    },
    xhigh: {
      v: 1.14,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 8 AA ladders"],
    },
    max: {
      v: 1.17,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 7 AA ladders"],
    },
  },
};
