// tinker-ui/src/panels/aa-effort-estimate.ts
// GENERATED by model-rank-refresh/scripts/estimate_effort_index.py — do not hand-edit.
// Retrieved: 2026-10-03T03:52:18+00:00
//
// ESTIMATED Artificial Analysis Intelligence Index for (family, effort) cells AA did
// not publish. the architect 2026-09-02: approximate from other measurements, as long as the
// chart never confuses an estimate with a measurement. Two methods, both named on
// every cell:
//   benchmark-fit — R²-weighted mean of per-benchmark linear fits AA ~ a + b·score,
//                   fitted on cells AA DID score at that effort; basis lists the
//                   benchmarks that ran this model at this effort (Epoch AI hub,
//                   LMArena text Elo).
//   ladder-shape  — the model's nearest AA-measured rung × the mean AA ratio
//                   between those two efforts over AA's own multi-rung families.
//                   Assumes an average ladder shape; sd is the spread of those ratios.
//   blend         — both, inverse-variance weighted.
// Every estimate is clamped between the model's measured neighbours and kept
// non-decreasing across efforts (pool-adjacent-violators), because a ladder
// whose 'high' outscores its measured 'max' is noise, not a finding.
// A cell AA measured is NEVER here — aa-effort-index.ts wins.
//
// Fits kept (n ≥ 6, R² ≥ 0.55):
//   Balrog: n=6 R²=0.92 rmse=3.8
//   GSO-Bench: n=6 R²=0.91 rmse=3.1
//   FrontierMath-2025-02-28-Private: n=16 R²=0.90 rmse=3.0
//   FrontierMath-Tier-4-2025-07-01-Private: n=16 R²=0.88 rmse=3.2
//   OSWorld 2.0: n=10 R²=0.88 rmse=2.1
//   ARC-AGI-2: n=83 R²=0.86 rmse=4.5
//   Aider polyglot: n=6 R²=0.86 rmse=1.9
//   FrontierSWE: n=15 R²=0.85 rmse=3.0
//   VPCT: n=8 R²=0.85 rmse=2.2
//   FrontierMath-Tiers-1-3-v2-Private: n=48 R²=0.83 rmse=5.5
//   LMCA: n=71 R²=0.81 rmse=4.8
//   SWE-Bench verified: n=9 R²=0.81 rmse=3.1
//   APEX-Agents: n=12 R²=0.81 rmse=3.2
//   ARC-AGI: n=84 R²=0.80 rmse=5.3
//   DeepSWE: n=55 R²=0.80 rmse=3.3
//   EBR-bench: n=18 R²=0.79 rmse=4.2
//   DTBench: n=71 R²=0.75 rmse=5.5
//   WeirdML: n=38 R²=0.75 rmse=6.3
//   LMArena text Elo: n=19 R²=0.74 rmse=6.9
//   ProofBench: n=27 R²=0.73 rmse=5.7
//   SimpleBench: n=9 R²=0.72 rmse=6.7
//   FrontierCode: n=11 R²=0.69 rmse=2.7
//   FrontierMath-Tier-4-v2-Private: n=47 R²=0.65 rmse=6.8
//   Mystery Game Puzzles: n=56 R²=0.64 rmse=8.0
//   OTIS Mock AIME 2024-2025: n=63 R²=0.62 rmse=7.9
//   GPQA diamond: n=61 R²=0.62 rmse=7.9
//   Furniture Assembly: n=25 R²=0.60 rmse=4.6
//   SimpleQA Verified: n=42 R²=0.57 rmse=7.4
//   PostTrainBench: n=6 R²=0.56 rmse=3.6

import type { AaEffort } from "./aa-effort-index.js";

export interface AaEstimate {
  /** Estimated AA Intelligence Index. */
  v: number;
  /** Spread of the estimate, AA points. */
  sd: number;
  method: "benchmark-fit" | "ladder-shape" | "blend";
  /** Benchmarks (or the AA-ladder delta) the number rests on. */
  basis: string[];
}

export const AA_EFFORT_ESTIMATE: Record<string, Partial<Record<AaEffort, AaEstimate>>> = {
  "claude-fable-5": {
    low: {
      v: 36.52,
      sd: 4.05,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DTBench",
        "DeepSWE",
        "GPQA diamond",
        "LMCA",
        "OTIS Mock AIME 2024-2025",
        "max\u2192low ratio over 14 AA ladders",
      ],
    },
    medium: {
      v: 41.93,
      sd: 3.28,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DTBench",
        "DeepSWE",
        "LMCA",
        "max\u2192medium ratio over 12 AA ladders",
      ],
    },
    high: {
      v: 44.62,
      sd: 2.67,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DTBench",
        "DeepSWE",
        "GPQA diamond",
        "LMCA",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
        "max\u2192high ratio over 13 AA ladders",
      ],
    },
    xhigh: {
      v: 46.8,
      sd: 1.61,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DTBench",
        "DeepSWE",
        "LMCA",
        "SimpleQA Verified",
        "max\u2192xhigh ratio over 13 AA ladders",
      ],
    },
  },
  "claude-fable-5-1": {
    minimal: {
      v: 27.62,
      sd: 4.38,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "claude-opus-4-5": {
    high: { v: 33.17, sd: 5.4, method: "benchmark-fit", basis: ["DTBench", "LMCA"] },
  },
  "claude-opus-4-6-adaptive": {
    low: {
      v: 22.76,
      sd: 2.85,
      method: "blend",
      basis: ["Mystery Game Puzzles", "max\u2192low ratio over 14 AA ladders"],
    },
    medium: {
      v: 26.24,
      sd: 2.82,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 12 AA ladders"],
    },
    high: {
      v: 30.29,
      sd: 1.72,
      method: "blend",
      basis: [
        "GSO-Bench",
        "WeirdML",
        "max\u2192high ratio over 13 AA ladders",
        "pooled for ladder order",
      ],
    },
    xhigh: {
      v: 30.29,
      sd: 1.08,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 13 AA ladders", "pooled for ladder order"],
    },
  },
  "claude-opus-4-7": {
    low: {
      v: 33.13,
      sd: 3.08,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "max\u2192low ratio over 14 AA ladders"],
    },
    medium: {
      v: 36.03,
      sd: 2.9,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "max\u2192medium ratio over 12 AA ladders"],
    },
    high: {
      v: 37.61,
      sd: 2.14,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GSO-Bench",
        "WeirdML",
        "max\u2192high ratio over 13 AA ladders",
      ],
    },
    xhigh: {
      v: 38.37,
      sd: 1.35,
      method: "blend",
      basis: [
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "PostTrainBench",
        "SimpleQA Verified",
        "max\u2192xhigh ratio over 13 AA ladders",
      ],
    },
  },
  "claude-opus-4-8": {
    low: {
      v: 31.89,
      sd: 3.41,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DeepSWE",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "max\u2192low ratio over 14 AA ladders",
      ],
    },
    medium: {
      v: 35.95,
      sd: 3.06,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DeepSWE",
        "WeirdML",
        "max\u2192medium ratio over 12 AA ladders",
      ],
    },
    high: {
      v: 38.38,
      sd: 2.15,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DeepSWE",
        "PostTrainBench",
        "max\u2192high ratio over 13 AA ladders",
      ],
    },
    xhigh: {
      v: 39.48,
      sd: 1.39,
      method: "blend",
      basis: [
        "DeepSWE",
        "Mystery Game Puzzles",
        "WeirdML",
        "max\u2192xhigh ratio over 13 AA ladders",
      ],
    },
  },
  "claude-opus-5": {
    minimal: {
      v: 25.31,
      sd: 4.01,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "claude-opus-5-5": {
    minimal: {
      v: 28.93,
      sd: 4.58,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "claude-sonnet-4-6-adaptive": {
    low: {
      v: 22.11,
      sd: 2.7,
      method: "blend",
      basis: ["Mystery Game Puzzles", "max\u2192low ratio over 14 AA ladders"],
    },
    medium: {
      v: 25.7,
      sd: 2.46,
      method: "blend",
      basis: [
        "GPQA diamond",
        "OSWorld 2.0",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
        "max\u2192medium ratio over 12 AA ladders",
      ],
    },
    high: {
      v: 27.47,
      sd: 1.69,
      method: "blend",
      basis: [
        "APEX-Agents",
        "ARC-AGI",
        "ARC-AGI-2",
        "DeepSWE",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "max\u2192high ratio over 13 AA ladders",
      ],
    },
    xhigh: {
      v: 28.42,
      sd: 1.02,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 13 AA ladders"],
    },
  },
  "claude-sonnet-5": {
    minimal: {
      v: 15.84,
      sd: 2.51,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "claude-sonnet-5-5": {
    minimal: {
      v: 23.06,
      sd: 3.65,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "deepseek-v4-1-flash": {
    low: {
      v: 28.21,
      sd: 3.77,
      method: "ladder-shape",
      basis: ["max\u2192low ratio over 14 AA ladders"],
    },
    medium: {
      v: 32.41,
      sd: 3.48,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 12 AA ladders"],
    },
    high: {
      v: 35.68,
      sd: 2.27,
      method: "ladder-shape",
      basis: ["max\u2192high ratio over 13 AA ladders"],
    },
    xhigh: {
      v: 37.3,
      sd: 1.34,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 13 AA ladders"],
    },
  },
  "deepseek-v4-flash": {
    low: {
      v: 27.48,
      sd: 2.82,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "max\u2192low ratio over 14 AA ladders"],
    },
    medium: {
      v: 28.2,
      sd: 3.03,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 12 AA ladders"],
    },
    high: {
      v: 31.07,
      sd: 1.94,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "WeirdML", "max\u2192high ratio over 13 AA ladders"],
    },
    xhigh: {
      v: 32.46,
      sd: 1.16,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 13 AA ladders"],
    },
  },
  "deepseek-v4-flash-0420": {
    minimal: {
      v: 14.42,
      sd: 2.13,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 20.41,
      sd: 2.37,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 23.2,
      sd: 1.93,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 25.54,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 27.08,
      sd: 1.74,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "deepseek-v4-flash-vision": {
    low: {
      v: 24.91,
      sd: 3.33,
      method: "ladder-shape",
      basis: ["max\u2192low ratio over 14 AA ladders"],
    },
    medium: {
      v: 28.62,
      sd: 3.08,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 12 AA ladders"],
    },
    high: {
      v: 31.5,
      sd: 2.01,
      method: "ladder-shape",
      basis: ["max\u2192high ratio over 13 AA ladders"],
    },
    xhigh: {
      v: 32.94,
      sd: 1.18,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 13 AA ladders"],
    },
  },
  "deepseek-v4-pro": {
    low: {
      v: 29.57,
      sd: 2.89,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "max\u2192low ratio over 14 AA ladders",
        "pooled for ladder order",
      ],
    },
    medium: {
      v: 29.57,
      sd: 3.18,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 12 AA ladders", "pooled for ladder order"],
    },
    high: {
      v: 32.67,
      sd: 2.02,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierCode",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
        "max\u2192high ratio over 13 AA ladders",
      ],
    },
    xhigh: {
      v: 34.03,
      sd: 1.22,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 13 AA ladders"],
    },
  },
  "deepseek-v4-pro-0424": {
    minimal: {
      v: 17.81,
      sd: 2.63,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 25.2,
      sd: 2.93,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 28.65,
      sd: 2.38,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 30.45,
      sd: 0.99,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders", "clamped to measured neighbours"],
    },
  },
  "gemini-3-1-flash-lite": {
    minimal: {
      v: 12.3,
      sd: 11.24,
      method: "benchmark-fit",
      basis: ["FrontierMath-Tiers-1-3-v2-Private", "GPQA diamond", "OTIS Mock AIME 2024-2025"],
    },
    low: {
      v: 14.0,
      sd: 9.95,
      method: "benchmark-fit",
      basis: ["FrontierMath-Tiers-1-3-v2-Private", "GPQA diamond", "OTIS Mock AIME 2024-2025"],
    },
    high: {
      v: 23.03,
      sd: 7.59,
      method: "benchmark-fit",
      basis: [
        "DTBench",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "LMCA",
        "OTIS Mock AIME 2024-2025",
      ],
    },
  },
  "gemini-3-1-flash-lite-preview": {
    minimal: {
      v: 9.2,
      sd: 1.36,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 13.02,
      sd: 1.51,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 14.8,
      sd: 1.23,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 16.29,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 17.27,
      sd: 1.11,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "gemini-3-1-pro": {
    low: {
      v: 37.48,
      sd: 6.8,
      method: "benchmark-fit",
      basis: ["DTBench", "LMCA", "Mystery Game Puzzles"],
    },
    medium: {
      v: 39.33,
      sd: 7.03,
      method: "benchmark-fit",
      basis: ["DTBench", "LMCA", "Mystery Game Puzzles"],
    },
    high: {
      v: 40.42,
      sd: 7.75,
      method: "benchmark-fit",
      basis: [
        "DTBench",
        "Furniture Assembly",
        "GPQA diamond",
        "LMCA",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
      ],
    },
  },
  "gemini-3-5-flash": {
    low: {
      v: 29.81,
      sd: 1.92,
      method: "blend",
      basis: [
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "medium\u2192low ratio over 23 AA ladders",
      ],
    },
    xhigh: {
      v: 34.15,
      sd: 1.07,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 36.2,
      sd: 2.33,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "gemini-3-5-flash-lite": {
    minimal: {
      v: 13.19,
      sd: 1.9,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "high\u2192minimal ratio over 4 AA ladders",
      ],
    },
    low: {
      v: 18.54,
      sd: 2.1,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "high\u2192low ratio over 24 AA ladders",
      ],
    },
    medium: {
      v: 20.75,
      sd: 1.66,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 23.22,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 24.62,
      sd: 1.58,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "gemini-3-6-flash": {
    minimal: {
      v: 20.5,
      sd: 2.83,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "high\u2192minimal ratio over 4 AA ladders",
      ],
    },
    low: {
      v: 28.91,
      sd: 3.0,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "high\u2192low ratio over 24 AA ladders",
      ],
    },
    medium: {
      v: 33.17,
      sd: 2.38,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 35.59,
      sd: 1.12,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 37.73,
      sd: 2.43,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "gemini-3-7-flash": {
    minimal: {
      v: 22.37,
      sd: 3.54,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    xhigh: {
      v: 40.91,
      sd: 1.29,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 43.37,
      sd: 2.79,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "gemini-3-8-flash": {
    minimal: {
      v: 22.46,
      sd: 3.56,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    xhigh: {
      v: 42.87,
      sd: 1.35,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 45.45,
      sd: 2.92,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "gemini-3-flash": {
    minimal: { v: 31.52, sd: 7.97, method: "benchmark-fit", basis: ["Mystery Game Puzzles"] },
    low: { v: 32.04, sd: 7.97, method: "benchmark-fit", basis: ["Mystery Game Puzzles"] },
    high: {
      v: 35.16,
      sd: 8.86,
      method: "benchmark-fit",
      basis: [
        "DTBench",
        "GPQA diamond",
        "LMCA",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
      ],
    },
  },
  "gemini-3-flash-thinking": {
    minimal: { v: 38.17, sd: 6.92, method: "benchmark-fit", basis: ["LMArena text Elo"] },
  },
  "gemini-3-pro": {
    minimal: {
      v: 16.54,
      sd: 2.44,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    medium: {
      v: 25.52,
      sd: 1.8,
      method: "ladder-shape",
      basis: ["low\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 29.28,
      sd: 0.92,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 31.05,
      sd: 2.0,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "gemma-4-26b-a4b-it": {
    minimal: {
      v: 25.07,
      sd: 8.96,
      method: "benchmark-fit",
      basis: ["GPQA diamond", "OTIS Mock AIME 2024-2025"],
    },
  },
  "gemma-4-31b-it": {
    minimal: {
      v: 23.24,
      sd: 7.9,
      method: "benchmark-fit",
      basis: ["GPQA diamond", "OTIS Mock AIME 2024-2025"],
    },
  },
  "glm-5-2": {
    minimal: {
      v: 26.41,
      sd: 7.97,
      method: "benchmark-fit",
      basis: ["Mystery Game Puzzles", "pooled for ladder order"],
    },
    low: {
      v: 26.41,
      sd: 2.99,
      method: "blend",
      basis: [
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "max\u2192low ratio over 14 AA ladders",
        "pooled for ladder order",
      ],
    },
    medium: {
      v: 27.53,
      sd: 2.79,
      method: "blend",
      basis: ["Mystery Game Puzzles", "max\u2192medium ratio over 12 AA ladders"],
    },
    high: {
      v: 30.68,
      sd: 1.81,
      method: "blend",
      basis: ["DeepSWE", "WeirdML", "max\u2192high ratio over 13 AA ladders"],
    },
    xhigh: {
      v: 31.87,
      sd: 1.14,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 13 AA ladders"],
    },
  },
  "glm-5-3": {
    medium: {
      v: 39.22,
      sd: 2.76,
      method: "ladder-shape",
      basis: ["low\u2192medium ratio over 23 AA ladders"],
    },
    high: {
      v: 41.52,
      sd: 4.78,
      method: "ladder-shape",
      basis: ["low\u2192high ratio over 24 AA ladders"],
    },
    xhigh: {
      v: 42.34,
      sd: 1.52,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 13 AA ladders"],
    },
  },
  "glm-5-3-flash": {
    low: {
      v: 29.89,
      sd: 4.0,
      method: "ladder-shape",
      basis: ["max\u2192low ratio over 14 AA ladders"],
    },
    medium: {
      v: 34.35,
      sd: 3.69,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 12 AA ladders"],
    },
    high: {
      v: 37.8,
      sd: 2.41,
      method: "ladder-shape",
      basis: ["max\u2192high ratio over 13 AA ladders"],
    },
    xhigh: {
      v: 39.53,
      sd: 1.42,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 13 AA ladders"],
    },
  },
  "gpt-5": {
    xhigh: {
      v: 24.07,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 25.52,
      sd: 1.64,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "gpt-5-1": {
    minimal: {
      v: 14.63,
      sd: 2.16,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 20.52,
      sd: 2.28,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "high\u2192low ratio over 24 AA ladders",
      ],
    },
    medium: {
      v: 23.56,
      sd: 1.89,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "VPCT",
        "high\u2192medium ratio over 23 AA ladders",
      ],
    },
    xhigh: {
      v: 25.91,
      sd: 0.81,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 27.47,
      sd: 1.77,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "gpt-5-1-codex": {
    minimal: {
      v: 14.02,
      sd: 2.07,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 19.84,
      sd: 2.3,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 22.55,
      sd: 1.87,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 24.82,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 26.31,
      sd: 1.69,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "gpt-5-1-codex-mini": {
    minimal: {
      v: 12.05,
      sd: 1.78,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 17.06,
      sd: 1.98,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 19.39,
      sd: 1.61,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 21.35,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 22.63,
      sd: 1.46,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "gpt-5-2": {
    minimal: {
      v: 14.96,
      sd: 2.37,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 23.31,
      sd: 1.52,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "WeirdML",
        "medium\u2192low ratio over 23 AA ladders",
      ],
    },
    high: {
      v: 28.37,
      sd: 2.07,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "GPQA diamond",
        "GSO-Bench",
        "LMArena text Elo",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SWE-Bench verified",
        "SimpleBench",
        "SimpleQA Verified",
        "VPCT",
        "medium\u2192high ratio over 23 AA ladders",
      ],
    },
    max: {
      v: 32.25,
      sd: 1.15,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 13 AA ladders"],
    },
  },
  "gpt-5-2-codex": {
    low: {
      v: 21.8,
      sd: 2.31,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 17 AA ladders"],
    },
    medium: {
      v: 24.89,
      sd: 1.88,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 18 AA ladders"],
    },
    high: {
      v: 27.24,
      sd: 0.84,
      method: "ladder-shape",
      basis: ["xhigh\u2192high ratio over 15 AA ladders"],
    },
    max: {
      v: 30.18,
      sd: 1.07,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 13 AA ladders"],
    },
  },
  "gpt-5-2-pro": {
    medium: { v: 33.72, sd: 5.8, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    high: { v: 37.41, sd: 5.1, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    xhigh: {
      v: 40.62,
      sd: 5.94,
      method: "benchmark-fit",
      basis: ["ARC-AGI", "FrontierMath-Tier-4-v2-Private", "FrontierMath-Tiers-1-3-v2-Private"],
    },
  },
  "gpt-5-3-codex": {
    low: {
      v: 24.86,
      sd: 2.63,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 17 AA ladders"],
    },
    medium: {
      v: 28.39,
      sd: 2.14,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 18 AA ladders"],
    },
    high: {
      v: 30.97,
      sd: 0.92,
      method: "blend",
      basis: ["SWE-Bench verified", "xhigh\u2192high ratio over 15 AA ladders"],
    },
    max: {
      v: 34.42,
      sd: 1.23,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 13 AA ladders"],
    },
  },
  "gpt-5-4": {
    medium: {
      v: 31.99,
      sd: 2.12,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "low\u2192medium ratio over 23 AA ladders",
      ],
    },
    high: {
      v: 37.22,
      sd: 1.14,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "GSO-Bench",
        "OTIS Mock AIME 2024-2025",
        "PostTrainBench",
        "SWE-Bench verified",
        "xhigh\u2192high ratio over 15 AA ladders",
      ],
    },
    max: {
      v: 41.28,
      sd: 1.47,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 13 AA ladders"],
    },
  },
  "gpt-5-4-mini": {
    minimal: {
      v: 11.15,
      sd: 1.77,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 17.32,
      sd: 1.15,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tiers-1-3-v2-Private",
        "Mystery Game Puzzles",
        "medium\u2192low ratio over 23 AA ladders",
      ],
    },
    high: {
      v: 21.09,
      sd: 1.6,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "GPQA diamond",
        "LMArena text Elo",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "WeirdML",
        "medium\u2192high ratio over 23 AA ladders",
      ],
    },
    max: {
      v: 25.49,
      sd: 0.91,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 13 AA ladders"],
    },
  },
  "gpt-5-4-nano": {
    minimal: {
      v: 11.3,
      sd: 1.79,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 17.57,
      sd: 1.16,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "medium\u2192low ratio over 23 AA ladders",
      ],
    },
    high: {
      v: 20.72,
      sd: 1.61,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "FrontierMath-Tier-4-v2-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "LMArena text Elo",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "ProofBench",
        "SimpleQA Verified",
        "WeirdML",
        "medium\u2192high ratio over 23 AA ladders",
        "clamped to measured neighbours",
      ],
    },
    max: {
      v: 21.94,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 13 AA ladders"],
    },
  },
  "gpt-5-4-pro": {
    xhigh: {
      v: 41.92,
      sd: 6.69,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-v2-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "SimpleQA Verified",
      ],
    },
  },
  "gpt-5-5": {
    minimal: {
      v: 19.09,
      sd: 3.02,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    max: {
      v: 40.62,
      sd: 1.45,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 13 AA ladders"],
    },
  },
  "gpt-5-5-pro": {
    high: {
      v: 44.2,
      sd: 5.59,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "SimpleBench",
        "pooled for ladder order",
      ],
    },
    xhigh: {
      v: 44.2,
      sd: 6.53,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "DTBench",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "FrontierMath-Tier-4-v2-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "LMCA",
        "OTIS Mock AIME 2024-2025",
        "pooled for ladder order",
      ],
    },
  },
  "gpt-5-6-luna": {
    minimal: {
      v: 14.14,
      sd: 2.24,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "gpt-5-6-sol": {
    minimal: {
      v: 22.15,
      sd: 3.51,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "gpt-5-6-terra": {
    minimal: {
      v: 16.99,
      sd: 2.69,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "gpt-5-codex": {
    minimal: {
      v: 14.72,
      sd: 2.17,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 20.83,
      sd: 2.42,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 23.68,
      sd: 1.97,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 26.06,
      sd: 0.82,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 27.63,
      sd: 1.78,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "gpt-5-mini": {
    low: {
      v: 16.77,
      sd: 1.18,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tiers-1-3-v2-Private",
        "medium\u2192low ratio over 23 AA ladders",
        "clamped to measured neighbours",
      ],
    },
    xhigh: {
      v: 20.6,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders", "clamped to measured neighbours"],
    },
    max: {
      v: 20.6,
      sd: 1.2,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders", "clamped to measured neighbours"],
    },
  },
  "gpt-5-nano": {
    low: {
      v: 10.96,
      sd: 0.8,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
        "medium\u2192low ratio over 23 AA ladders",
      ],
    },
    xhigh: {
      v: 13.61,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 14.43,
      sd: 0.93,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "gpt-5-pro": {
    high: {
      v: 31.24,
      sd: 6.76,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "FrontierMath-Tier-4-v2-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "SimpleBench",
        "WeirdML",
      ],
    },
  },
  "gpt-6-1-sol": {
    minimal: {
      v: 26.98,
      sd: 4.27,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "gpt-6-astra": {
    minimal: {
      v: 27.99,
      sd: 4.43,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "gpt-6-luna": {
    minimal: {
      v: 16.9,
      sd: 2.68,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "gpt-6-sol": {
    minimal: {
      v: 22.48,
      sd: 3.56,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
  },
  "gpt-oss-120b": {
    minimal: {
      v: 6.86,
      sd: 1.01,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    medium: {
      v: 11.6,
      sd: 0.82,
      method: "blend",
      basis: [
        "Mystery Game Puzzles",
        "WeirdML",
        "low\u2192medium ratio over 23 AA ladders",
        "clamped to measured neighbours",
      ],
    },
    xhigh: {
      v: 12.15,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 12.88,
      sd: 0.83,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "gpt-oss-20b": {
    minimal: {
      v: 5.3,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    xhigh: {
      v: 9.95,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders", "clamped to measured neighbours"],
    },
    max: {
      v: 9.96,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "grok-3-mini": {
    low: { v: 13.53, sd: 6.61, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    high: { v: 15.51, sd: 7.0, method: "benchmark-fit", basis: ["LMArena text Elo", "WeirdML"] },
  },
  "grok-3-mini-beta": {
    low: {
      v: 11.39,
      sd: 8.29,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "Aider polyglot",
        "FrontierMath-2025-02-28-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
      ],
    },
    high: {
      v: 16.27,
      sd: 8.8,
      method: "benchmark-fit",
      basis: [
        "Aider polyglot",
        "FrontierMath-2025-02-28-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "WeirdML",
      ],
    },
  },
  "grok-3-mini-reasoning": {
    minimal: {
      v: 8.65,
      sd: 1.28,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 12.24,
      sd: 1.42,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 13.91,
      sd: 1.15,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 15.32,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 16.24,
      sd: 1.04,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "grok-4-0709": {
    high: { v: 19.87, sd: 1.86, method: "benchmark-fit", basis: ["Aider polyglot"] },
  },
  "grok-4-3": {
    minimal: {
      v: 13.99,
      sd: 2.22,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    xhigh: {
      v: 26.06,
      sd: 0.82,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 27.63,
      sd: 1.78,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "grok-4-5": {
    minimal: {
      v: 22.96,
      sd: 3.39,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 32.45,
      sd: 3.2,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 37.06,
      sd: 2.65,
      method: "blend",
      basis: ["ARC-AGI", "ARC-AGI-2", "high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 40.65,
      sd: 1.28,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 43.1,
      sd: 2.77,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "grok-4-6": {
    minimal: {
      v: 24.19,
      sd: 3.83,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    max: {
      v: 46.81,
      sd: 1.67,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 13 AA ladders"],
    },
  },
  "grok-4-7": {
    minimal: {
      v: 27.4,
      sd: 4.04,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    medium: {
      v: 46.33,
      sd: 3.4,
      method: "ladder-shape",
      basis: ["low\u2192medium ratio over 23 AA ladders", "clamped to measured neighbours"],
    },
    max: {
      v: 49.19,
      sd: 1.75,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 13 AA ladders"],
    },
  },
  "hypernova-60b": {
    minimal: {
      v: 6.94,
      sd: 1.02,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 9.83,
      sd: 1.14,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 11.17,
      sd: 0.93,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 12.29,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 13.03,
      sd: 0.84,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  inkling: {
    low: {
      v: 19.11,
      sd: 2.02,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 17 AA ladders"],
    },
    medium: {
      v: 21.82,
      sd: 1.65,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 18 AA ladders"],
    },
    high: {
      v: 23.68,
      sd: 0.79,
      method: "blend",
      basis: ["WeirdML", "xhigh\u2192high ratio over 15 AA ladders"],
    },
    max: {
      v: 26.46,
      sd: 0.94,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 13 AA ladders"],
    },
  },
  "inkling-small": {
    minimal: { v: 20.85, sd: 5.24, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    low: { v: 21.83, sd: 5.54, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    medium: { v: 26.4, sd: 6.48, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    high: {
      v: 31.25,
      sd: 5.93,
      method: "benchmark-fit",
      basis: ["ARC-AGI", "ARC-AGI-2", "pooled for ladder order"],
    },
    xhigh: {
      v: 31.25,
      sd: 8.57,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tier-4-v2-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "pooled for ladder order",
      ],
    },
  },
  "k2-think-v2": {
    minimal: {
      v: 6.8,
      sd: 1.0,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 9.62,
      sd: 1.12,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 10.94,
      sd: 0.91,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 12.04,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 12.77,
      sd: 0.82,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "k2-v2": {
    minimal: {
      v: 5.09,
      sd: 0.81,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    xhigh: {
      v: 10.34,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 10.96,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "kimi-k3": {
    medium: {
      v: 34.38,
      sd: 2.42,
      method: "ladder-shape",
      basis: ["low\u2192medium ratio over 23 AA ladders"],
    },
    high: {
      v: 36.76,
      sd: 3.52,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "low\u2192high ratio over 24 AA ladders",
      ],
    },
    xhigh: {
      v: 41.22,
      sd: 1.48,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 13 AA ladders"],
    },
  },
  "mercury-2": {
    minimal: {
      v: 8.14,
      sd: 1.2,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 11.53,
      sd: 1.34,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 13.1,
      sd: 1.09,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 14.42,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 15.29,
      sd: 0.98,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "mimo-v2-6-pro": {
    low: {
      v: 33.12,
      sd: 4.43,
      method: "ladder-shape",
      basis: ["max\u2192low ratio over 14 AA ladders"],
    },
    medium: {
      v: 38.06,
      sd: 4.09,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 12 AA ladders"],
    },
    high: {
      v: 41.89,
      sd: 2.67,
      method: "ladder-shape",
      basis: ["max\u2192high ratio over 13 AA ladders"],
    },
    xhigh: {
      v: 43.8,
      sd: 1.57,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 13 AA ladders"],
    },
  },
  mistral: {
    medium: { v: -24.02, sd: 6.92, method: "benchmark-fit", basis: ["LMArena text Elo"] },
  },
  "mistral-medium-3-5": {
    minimal: {
      v: 8.39,
      sd: 1.24,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 11.88,
      sd: 1.38,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 13.5,
      sd: 1.12,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 14.86,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 15.76,
      sd: 1.01,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "muse-glimmer": {
    minimal: {
      v: 10.34,
      sd: 1.52,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 14.63,
      sd: 1.7,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 16.63,
      sd: 1.38,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 18.3,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 19.41,
      sd: 1.25,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "muse-spark-1-1": {
    low: {
      v: 25.79,
      sd: 2.73,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 17 AA ladders"],
    },
    medium: {
      v: 29.46,
      sd: 2.22,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 18 AA ladders"],
    },
    high: {
      v: 32.42,
      sd: 0.98,
      method: "blend",
      basis: ["DTBench", "LMCA", "xhigh\u2192high ratio over 15 AA ladders"],
    },
    max: {
      v: 35.72,
      sd: 1.27,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 13 AA ladders"],
    },
  },
  "muse-spark-1-2": {
    low: {
      v: 30.27,
      sd: 3.2,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 17 AA ladders"],
    },
    medium: {
      v: 34.57,
      sd: 2.61,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 18 AA ladders"],
    },
    high: {
      v: 37.82,
      sd: 1.17,
      method: "ladder-shape",
      basis: ["xhigh\u2192high ratio over 15 AA ladders"],
    },
    max: {
      v: 41.91,
      sd: 1.49,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 13 AA ladders"],
    },
  },
  "muse-spark-1-3": {
    low: {
      v: 34.47,
      sd: 3.65,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 17 AA ladders"],
    },
    medium: {
      v: 39.37,
      sd: 2.97,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 18 AA ladders"],
    },
    high: {
      v: 43.07,
      sd: 1.33,
      method: "ladder-shape",
      basis: ["xhigh\u2192high ratio over 15 AA ladders"],
    },
  },
  "nova-2-0-lite-reasoning": {
    minimal: {
      v: 7.05,
      sd: 1.12,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    xhigh: {
      v: 14.01,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 14.85,
      sd: 0.96,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "nova-2-0-omni-reasoning": {
    minimal: {
      v: 7.71,
      sd: 1.22,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    high: {
      v: 14.43,
      sd: 1.12,
      method: "ladder-shape",
      basis: ["medium\u2192high ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 15.72,
      sd: 1.24,
      method: "ladder-shape",
      basis: ["medium\u2192xhigh ratio over 18 AA ladders"],
    },
    max: {
      v: 16.81,
      sd: 1.88,
      method: "ladder-shape",
      basis: ["medium\u2192max ratio over 12 AA ladders"],
    },
  },
  "nova-2-0-pro-reasoning": {
    minimal: {
      v: 7.99,
      sd: 1.27,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    high: {
      v: 14.97,
      sd: 1.17,
      method: "ladder-shape",
      basis: ["medium\u2192high ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 16.3,
      sd: 1.29,
      method: "ladder-shape",
      basis: ["medium\u2192xhigh ratio over 18 AA ladders"],
    },
    max: {
      v: 17.44,
      sd: 1.95,
      method: "ladder-shape",
      basis: ["medium\u2192max ratio over 12 AA ladders"],
    },
  },
  o1: {
    low: {
      v: 13.14,
      sd: 8.2,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
      ],
    },
    medium: {
      v: 17.31,
      sd: 7.79,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "SimpleBench",
        "VPCT",
      ],
    },
    high: {
      v: 18.14,
      sd: 8.64,
      method: "benchmark-fit",
      basis: [
        "Aider polyglot",
        "DTBench",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "LMCA",
        "OTIS Mock AIME 2024-2025",
        "SimpleBench",
        "SimpleQA Verified",
        "WeirdML",
      ],
    },
  },
  "o1-mini": {
    medium: {
      v: 7.41,
      sd: 6.93,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "FrontierMath-2025-02-28-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "SimpleBench",
        "WeirdML",
        "pooled for ladder order",
      ],
    },
    high: {
      v: 7.41,
      sd: 6.8,
      method: "benchmark-fit",
      basis: [
        "FrontierMath-2025-02-28-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "pooled for ladder order",
      ],
    },
  },
  "o1-pro": {
    low: { v: 11.87, sd: 5.31, method: "benchmark-fit", basis: ["ARC-AGI"] },
  },
  o3: {
    low: {
      v: 16.98,
      sd: 7.55,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
      ],
    },
    medium: {
      v: 21.78,
      sd: 7.24,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "Aider polyglot",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SWE-Bench verified",
        "VPCT",
      ],
    },
    high: {
      v: 24.84,
      sd: 8.27,
      method: "benchmark-fit",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "Aider polyglot",
        "DTBench",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "GSO-Bench",
        "LMCA",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleBench",
        "SimpleQA Verified",
        "WeirdML",
      ],
    },
  },
  "o3-mini": {
    minimal: {
      v: 6.49,
      sd: 0.96,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 9.22,
      sd: 1.06,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "GSO-Bench",
        "OTIS Mock AIME 2024-2025",
        "high\u2192low ratio over 24 AA ladders",
      ],
    },
    medium: {
      v: 10.49,
      sd: 0.86,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "Aider polyglot",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "high\u2192medium ratio over 23 AA ladders",
      ],
    },
    xhigh: {
      v: 11.48,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 12.18,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "o3-pro": {
    low: { v: 19.63, sd: 5.06, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    medium: { v: 22.26, sd: 6.36, method: "benchmark-fit", basis: ["ARC-AGI", "ARC-AGI-2"] },
    high: {
      v: 25.4,
      sd: 6.32,
      method: "benchmark-fit",
      basis: ["ARC-AGI", "ARC-AGI-2", "Aider polyglot", "DTBench", "LMCA", "WeirdML"],
    },
  },
  "o4-mini": {
    minimal: {
      v: 9.85,
      sd: 1.45,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 14.0,
      sd: 1.58,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
        "high\u2192low ratio over 24 AA ladders",
      ],
    },
    medium: {
      v: 16.03,
      sd: 1.28,
      method: "blend",
      basis: [
        "ARC-AGI",
        "ARC-AGI-2",
        "FrontierMath-2025-02-28-Private",
        "FrontierMath-Tier-4-2025-07-01-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "GPQA diamond",
        "OTIS Mock AIME 2024-2025",
        "VPCT",
        "high\u2192medium ratio over 23 AA ladders",
      ],
    },
    xhigh: {
      v: 17.44,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 18.49,
      sd: 1.19,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "openai/gpt-oss-120b": {
    high: {
      v: 20.79,
      sd: 10.81,
      method: "benchmark-fit",
      basis: ["Aider polyglot", "GPQA diamond", "OTIS Mock AIME 2024-2025", "WeirdML"],
    },
  },
  "quasar-438b": {
    low: {
      v: 19.12,
      sd: 2.56,
      method: "ladder-shape",
      basis: ["max\u2192low ratio over 14 AA ladders"],
    },
    medium: {
      v: 21.97,
      sd: 2.36,
      method: "ladder-shape",
      basis: ["max\u2192medium ratio over 12 AA ladders"],
    },
    high: {
      v: 24.18,
      sd: 1.54,
      method: "ladder-shape",
      basis: ["max\u2192high ratio over 13 AA ladders"],
    },
    xhigh: {
      v: 25.28,
      sd: 0.91,
      method: "ladder-shape",
      basis: ["max\u2192xhigh ratio over 13 AA ladders"],
    },
  },
  "qwen2-5": {
    max: { v: 15.88, sd: 6.92, method: "benchmark-fit", basis: ["LMArena text Elo"] },
  },
  "qwen3-8-27b": {
    minimal: {
      v: 15.56,
      sd: 2.46,
      method: "ladder-shape",
      basis: ["medium\u2192minimal ratio over 4 AA ladders"],
    },
    high: {
      v: 29.14,
      sd: 2.27,
      method: "ladder-shape",
      basis: ["medium\u2192high ratio over 23 AA ladders"],
    },
    max: {
      v: 35.69,
      sd: 1.27,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 13 AA ladders"],
    },
  },
  "qwen3-8-max": {
    xhigh: {
      v: 38.08,
      sd: 6.43,
      method: "benchmark-fit",
      basis: [
        "DTBench",
        "DeepSWE",
        "FrontierMath-Tier-4-v2-Private",
        "FrontierMath-Tiers-1-3-v2-Private",
        "FrontierSWE",
        "Furniture Assembly",
        "GPQA diamond",
        "LMCA",
        "Mystery Game Puzzles",
        "OTIS Mock AIME 2024-2025",
        "SimpleQA Verified",
      ],
    },
  },
  "ring-2-6-1t": {
    low: {
      v: 12.71,
      sd: 1.34,
      method: "ladder-shape",
      basis: ["xhigh\u2192low ratio over 17 AA ladders"],
    },
    medium: {
      v: 14.51,
      sd: 1.1,
      method: "ladder-shape",
      basis: ["xhigh\u2192medium ratio over 18 AA ladders"],
    },
    high: {
      v: 15.88,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["xhigh\u2192high ratio over 15 AA ladders"],
    },
    max: {
      v: 17.6,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["xhigh\u2192max ratio over 13 AA ladders"],
    },
  },
  "sarvam-105b": {
    minimal: {
      v: 5.2,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 7.36,
      sd: 0.85,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 8.36,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 9.21,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 9.76,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "sarvam-30b": {
    minimal: {
      v: 3.88,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 5.49,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 6.24,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 6.87,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 7.28,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "sarvam-m-reasoning": {
    minimal: {
      v: 3.14,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 4.45,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 5.05,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 5.56,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 5.9,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "solar-open-100b-reasoning": {
    minimal: {
      v: 6.13,
      sd: 0.9,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 8.68,
      sd: 1.01,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 9.86,
      sd: 0.82,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 10.86,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 11.51,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "solar-pro-2-preview-reasoning": {
    minimal: {
      v: 5.36,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 7.59,
      sd: 0.88,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 8.63,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 9.5,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 10.07,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "solar-pro-2-reasoning": {
    minimal: {
      v: 4.43,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 6.27,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 7.13,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 7.85,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 8.32,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "solar-pro-3": {
    minimal: {
      v: 4.62,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 6.54,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 7.44,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 8.19,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 8.68,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "step-3-7-flash": {
    minimal: {
      v: 11.52,
      sd: 1.7,
      method: "ladder-shape",
      basis: ["high\u2192minimal ratio over 4 AA ladders"],
    },
    low: {
      v: 16.31,
      sd: 1.89,
      method: "ladder-shape",
      basis: ["high\u2192low ratio over 24 AA ladders"],
    },
    medium: {
      v: 18.54,
      sd: 1.54,
      method: "ladder-shape",
      basis: ["high\u2192medium ratio over 23 AA ladders"],
    },
    xhigh: {
      v: 20.41,
      sd: 0.8,
      method: "ladder-shape",
      basis: ["high\u2192xhigh ratio over 15 AA ladders"],
    },
    max: {
      v: 21.63,
      sd: 1.39,
      method: "ladder-shape",
      basis: ["high\u2192max ratio over 13 AA ladders"],
    },
  },
  "swe-2": {
    max: { v: 48.47, sd: 2.67, method: "benchmark-fit", basis: ["FrontierCode"] },
  },
};
