// tinker-ui/src/panels/aa-effort-estimate.ts
// GENERATED table now lives at src/shared/aa-effort-estimate.ts (regenerated by
// model-rank-refresh/scripts/estimate_effort_index.py). Re-export only.
export * from "../../../src/shared/aa-effort-estimate.js";
