/**
 * What `thalamus.panel` returns, for the mock gateway's states (charter phase G). One place, so the driver and any check
 * that wants the same data read the same fixtures.
 */
const NOW = Date.now();
const MIN = 60_000;

const decision = (i, over = {}) => ({
  id: `run-${i}:0`,
  ts: NOW - (i + 1) * 3 * MIN,
  lane: "embedded",
  mode: "shadow",
  incumbent: "claude-code/claude-opus-5",
  chosen: "claude-code/claude-sonnet-5-5",
  chosenEffort: "medium",
  pick: "claude-code/claude-sonnet-5-5",
  switchKind: "switch",
  switchReason: "cache-cold",
  nStar: null,
  wouldChange: true,
  degraded: false,
  private: false,
  price: 0.0312,
  incumbentPrice: 0.0994,
  reservedReason: null,
  options: [
    {
      key: "claude-code/claude-opus-5",
      effort: "high",
      feed: "thread",
      price: 0.0994,
      quality: 70,
    },
    {
      key: "claude-code/claude-sonnet-5-5",
      effort: "medium",
      feed: "thread",
      price: 0.0312,
      quality: 64,
    },
    { key: "xai/grok-4.7", effort: "high", feed: "brief", price: 0.0213, quality: 62 },
    { key: "claude-code/claude-haiku-4-5", effort: "", feed: "thread", price: 0.0098, quality: 52 },
  ],
  vetoes: [{ key: "openai-codex/gpt-6-astra", veto: "privacy" }],
  domain: "code",
  topic: "none",
  stepKind: "tool",
  ...over,
});
export const decisions = [
  decision(0),
  decision(1, {
    switchKind: "keep",
    switchReason: "kept-below-n-star",
    chosen: "claude-code/claude-opus-5",
    chosenEffort: "high",
    nStar: 4.75,
    wouldChange: false,
  }),
  decision(2, { switchKind: "keep", switchReason: "hand-picked", wouldChange: false, options: [] }),
  decision(3, {
    switchKind: "fresh",
    switchReason: "fresh-point",
    stepKind: "read",
    domain: "write",
  }),
  decision(4, { degraded: true, private: true, topic: "medical", reservedReason: "feasibility" }),
];
export const uses = [
  {
    taskId: "t1",
    ts: NOW - 4 * MIN,
    source: "tinker",
    private: false,
    shuffled: false,
    listShown: true,
    listReason: "shown",
    listSource: "jev",
    noneFits: 0.1,
    shown: [
      { cardId: "skill:translation-checker", rank: 1, prob: 0.62, fit: { value: "made-for" } },
      { cardId: "recipe:photo-sorter", rank: 2, prob: 0.2, fit: { value: "by-structure" } },
      { cardId: "plugin:budget-panel", rank: 3, prob: 0.08, fit: { value: "covers-part" } },
    ],
    used: [{ cardId: "recipe:photo-sorter", onList: true, rank: 2, via: "skill-tool" }],
    outcome: "done",
    mode: "shadow",
    taskKind: "code",
  },
  {
    taskId: "t2",
    ts: NOW - 30 * MIN,
    source: "channel:whatsapp",
    private: true,
    shuffled: true,
    listShown: true,
    listReason: "shown",
    listSource: "local",
    noneFits: 0.3,
    shown: [{ cardId: "skill:translation-checker", rank: 1, prob: 0.5 }],
    used: [],
    outcome: "retried",
    mode: "shadow",
    taskKind: "languages",
  },
  {
    taskId: "t3",
    ts: NOW - 50 * MIN,
    source: "tinker",
    private: false,
    shuffled: false,
    listShown: false,
    listReason: "none-leads",
    listSource: "jev",
    noneFits: 0.9,
    shown: [],
    used: [{ cardId: "skill:unlisted-helper", onList: false, via: "skill-tool" }],
    outcome: "corrected",
    mode: "shadow",
    taskKind: "general",
  },
];
const cardNames = {
  "skill:translation-checker": { name: "translation-checker", kind: "skill" },
  "recipe:photo-sorter": { name: "photo-sorter", kind: "recipe" },
  "plugin:budget-panel": { name: "budget-panel", kind: "plugin" },
  "skill:unlisted-helper": { name: "unlisted-helper", kind: "skill" },
};
const unit = (id, model, start, end, critical, over = {}) => ({
  unitId: id,
  copy: 0,
  model,
  effort: "",
  startSec: start,
  endSec: end,
  slackSec: critical ? 0 : 5,
  onCritical: critical,
  hedged: false,
  status: "placed",
  deps: [],
  ...over,
});
const plan = {
  planId: "contract",
  ts: NOW - 12 * MIN,
  mode: "shadow",
  units: [
    unit("plan", "claude-code/claude-opus-5", 0, 15, true),
    ...Array.from({ length: 6 }, (_, i) =>
      unit(
        `r${i + 1}`,
        i < 3 ? "xai/grok-4.7" : "claude-code/claude-sonnet-5-5",
        15,
        i === 6 ? 63 : 34 + (i === 4 ? 28 : 0),
        i === 4,
        { deps: ["plan"], hedged: i === 4 },
      ),
    ),
    { ...unit("r5", "claude-code/claude-haiku-4-5", 44, 62, true), copy: 1, status: "won" },
    unit("combine", "xai/grok-4.7", 62, 118, true, { deps: ["r1", "r2", "r3", "r4", "r5", "r6"] }),
    unit("check", "claude-code/claude-sonnet-5-5", 118, 149, true, { deps: ["combine"] }),
    unit("answer", "xai/grok-4.7", 149, 180, true, { deps: ["check"] }),
  ],
};
export const panel = (over = {}) => ({
  mode: "shadow",
  ts: NOW,
  today: { calls: 14, wouldChange: 3 },
  lastDecisionAt: decisions[0].ts,
  learning: { enabled: false, apply: false },
  decisions,
  uses,
  cardNames,
  plans: [plan],
  ...over,
});
export const EMPTY = panel({
  today: { calls: 0, wouldChange: 0 },
  lastDecisionAt: undefined,
  decisions: [],
  uses: [],
  cardNames: {},
  plans: [],
});
