/**
 * FORK: tinkerclaw-people — plugin entry.
 *
 * Registers the four `people.*` gateway methods that let the agent map a
 * free-text reference (name, email, phone, LID) to a per-person markdown
 * profile and read its current state + the delta since the last consultation.
 *
 * On-disk state lives at `~/.openclaw/workspace/memory/people/`:
 *   - `_aliases.json`   identity merge map (slug -> {emails,phones,lids,names})
 *   - `_state.json`     cron pointers + lastConsultedBythe user
 *   - `_index.md`       human-browsable index (regenerated by seed/cron)
 *   - `<slug>.md`       per-person profile
 *
 * The seed script (`scripts/seed.mjs`) bootstraps this directory from the
 * WhatsApp history DB. The cron summarizer
 * (`~/.openclaw/workspace/scripts/cron-people-profiles.sh`) keeps it fresh.
 */
import { definePluginEntry, type OpenClawPluginApi } from "./api.js";
import { registerPeopleGatewayMethods } from "./src/gateway.js";
import { resolvePeopleConfig, type PeoplePluginConfig } from "./src/paths.js";

export default definePluginEntry({
  id: "tinkerclaw-people",
  name: "People Profiles",
  description:
    "FORK: per-person markdown profiles auto-maintained from WhatsApp activity. Exposes people.* gateway methods.",
  register(api: OpenClawPluginApi) {
    const cfg = resolvePeopleConfig((api.pluginConfig ?? {}) as PeoplePluginConfig);
    registerPeopleGatewayMethods({ api, cfg });
    api.logger.info(
      `tinkerclaw-people: registered people.{resolve,read,list,update_consulted_at} (peopleDir=${cfg.peopleDir})`,
    );
  },
});
